argoproj/argo-events

docs/quickstart.md
There was no "hello-world.yaml" in the examples directory.
=> Update example sensor name.

controller/controller.go, controller/sensorjob.go
Testing Done:
1. Explicitly set the policy to "always" in the config-map. Verified that
the executor pod created had the imagePullPolicy of "always".
2. Modified the imagePullPolicy to "IfNotPresent" and the same steps above.
3. Removed the `executorImagePullPolicy` from the configMap. Verified that
the executor pod created had the imagePullPolicy of "always".
Closes #32.
=> Make executors imagePullPolicy configurable.

.argo-ci/builder/Dockerfile, .argo-ci/ci.yaml
This image includes the protobuf package and dependencies for installing it.
Also added the builder directory under .argo-ci which has the Dockerfile for the above image.
Testing done:
1. Built the image. Ran builds locally. They succeeded.
=> Use argoproj/argo-events-ci-builder:1.0 for argo-events builds.

store/url_test.go
Instead of reading a Github url, this commit starts and local http server and makes
the URLReader read from that server.
Closes #70.
=> Serve and read from local server for url test.

docs/custom-gateway.md, docs/gateway-guide.md, docs/sensor-guide.md
I found the links to github source tree in the docs are not valid.
=> Fix links of github tree references

docs/quickstart.md
Added `-n argo-events` to `minikube service` calls for consistency with rest of the quickstart guide.
=> Added missing namespace reference in quickstart guide

gateways/core/calendar/install.md
Comment says 10 seconds, but value is 55
=> Typo in comments for interval it should be 55 seconds not 10 seconds

Makefile
I'd like to build argo-events images with custom image prefix.
e.g. `IMAGE_NAMESPACE=dtaniwaki make github-image`
=> Allow to overwrite variables in Makefile

gateways/common/config.go, gateways/common/config_test.go, gateways/community/hdfs/config.go, gateways/community/hdfs/start.go, gateways/community/hdfs/validate.go, gateways/core/file/config.go, gateways/core/file/start.go, gateways/core/file/validate.go
I think supporting regexp paths is very useful when you want to monitor multiple files created in a specific directory.
=> Support regexp path

examples/gateways/secure-webhook-gateway-configmap.yaml, examples/gateways/secure-webhook.yaml, gateways/common/webhook.go
=> feature(): making webhook secure

Gopkg.lock, pkg/apis/sensor/v1alpha1/openapi_generated.go, pkg/apis/sensor/v1alpha1/types.go, sensors/event-handler_test.go, sensors/trigger.go, sensors/trigger_test.go
I set sensor's namespace as the default namespace of trigger resources, and added the tests.
I found OpenAPI spec is not updated when I executed `make openapi-gen`, so the PR also includes OpenAPI spec update for some other PRs.
Fixes #214
=> Handle empty namespace on trigger resources

gateways/event-source_test.go
[The CI](https://travis-ci.org/argoproj/argo-events/builds/505797464) failed because goroutine is still waiting for the channel when the context is gone.
```
panic: Fail in goroutine after TestEventSources has completed [recovered]
panic: Fail in goroutine after  has completed
```
I hope this fix solves the problem.
=> Fix goroutine error in test

examples/gateways/aws-sqs-gateway-configmap.yaml
When using this cm with the default value of 50, we get errors from aws
```
2019-04-02T15:57:07Z | warn  | msg: failed to process item from queue, waiting for next timeout |  error="InvalidParameterValue: Value 50 for parameter WaitTimeSeconds is invalid. Reason: Must be >= 0 and <= 20, if provided.\n\tstatus code: 400, request id: 58ec53b6-1b10-54be-a89f-06ab93836c82" event-source-name:notification
```
=> lower the wait timeout to a valid value

examples/sensors/slack.yaml
In slack example was a bug. Validation failed when creating the sensor.
=> Fix slack sensor example

gateways/transformer.go
Fix #283
Instead of using default HTTP Client, we should set timeout and connection limit.
Result:
The opening files stays at low:
```
while sleep 1; do lsof | grep gateway-c | wc -l; done
209
209
209
209
247
247
247
247
247
247
247
247
247
209
209
209
209
```
=> Set timeout and connection limit

docs/trigger.md
Tiny fix to documentation, the link on this page is broken: https://argoproj.github.io/argo-events/trigger/#git
=> Fix git trigger example link in documentation

docs/getting_started.md
remove the <> so they instructions can just be copy/pasted into a terminal
=> Make the instructions more explicit

examples/event-sources/webhook.yaml
[Documentation](https://argoproj.github.io/argo-events/getting_started/) tells the user to test the web hook by doing this:
```curl -d '{"message":"this is my first webhook"}' -H "Content-Type: application/json" -X POST `(minikube service --namespace=argo-events webhook-gateway-svc --url)`/example```
However, this will not work unless the example endpoint is set to ```/example```. This fixes it.
=> Make example consistent with documentation

gateways/core/calendar/config.go, gateways/core/calendar/start_test.go
At now, I am able to pass only string in userPayload field, but if I want to bind userPayload data to different places, sensor should receive it as object.
So, it would be great be able to use JSON objects in the userPayload field.
=> Ability to use JSON objects in the userPayload field for calendar events

Gopkg.lock, Gopkg.toml, docs/sensor.md, sensors/event-handler.go, sensors/event-handler_test.go
At now argo sensor requires to specify in dependency accurate gateway and event name, but in some cases multiple events should be processed by one sensor (e.g. multiple calendar events).
So it would be great to use globs in sensor dependencies (like `gateway-name:*`)
=> Wildcards in sensor dependencies

examples/gateways/gcp-pubsub.yaml
The name of the container in `argo-events/examples/gateways/gcp-pubsub.yaml` was named -        - `aws-sqs-events` instead of  `gcp-pubsub-events`
=> Fix container name of `/examples/gateways/gcp-pubsub.yaml`

docs/gateway.md, gateways/watcher.go
In some cases it's necessary to refer the eventSource in a different namespace. But gateway-client by default search configmaps in the gateway's namespace without any ability to change it. With this fix, you are able to refer the eventSource in custom namespace with a syntax `namespace/configmap-name`.
=> Added ability to refer the eventSource in a different namespace.

controllers/sensor/validate.go, docs/parameterization.md, examples/sensors/complete-trigger-parameterization.yaml, pkg/apis/sensor/v1alpha1/openapi_generated.go, pkg/apis/sensor/v1alpha1/types.go, sensors/trigger-params.go, sensors/trigger-params_test.go
Implemented an additional `operation` field for trigger parameters that
dictates what is to be done with the current value at `dest`. Possible
keyword values are:
- `overwrite` Overwrite the current value (default/prior behavior)
- `prepend` Prepend the value at `dest` with the value at `source.path`
- `append` Append the value at `dest` with the value at `source.path`
=> Support different trigger parameter operations (#315)

pkg/apis/sensor/v1alpha1/openapi_generated.go, pkg/apis/sensor/v1alpha1/types.go, store/git.go, store/git_test.go
Provides a `source.git.ref` field for specifying a specific non-branch
non-tag git ref at which to perform a checkout. Providing one will
result in a shallow (depth 1) clone of the repo and shallow subsequent
fetches.
The motivation for this change is to support sourcing of trigger
templates from Gerrit patchsets. Gerrit uses non-branch/-tag refs
extensively and specifically in this case stores change patchsets in
`refs/changes/[slice]/[change]/[patchset]`. While arbitrary refs are
kind of an obscure git feature, there very well may be other git based
systems utilizing them.
=> Support fetching/checkouts of non-branch/-tag git refs

examples/event-sources/gcp-pubsub.yaml
The example of pubsub configmap has the name `gcp-pubsub-configmap` while the example pubsub gateway uses `gcp-pubsub-event-source`. To keep it consistent with other examples and to make the example work out of the box, change the name of the the event source to `gcp-pubsub-event-source`.
=> Rename event-source of example gcp-pubsub to match gcp-pubsub gateway

examples/event-sources/gcp-pubsub.yaml, gateways/community/gcp-pubsub/start.go
Address some issues when using pubsub gateway
1. Only create pubsub topic when none exists. This allows the to use of existing topics rather throwing an error when the topic already exists.
2.Only create pubsub subscription when none exists. This allows the to use of existing subscriptions rather throwing an error when the subscription already exists.
3. Prefix  subscription name with the event source name to ensure the created subscription name starts with a letter.  https://github.com/argoproj/argo-events/issues/313 
4. Do not delete topic to not effect other services that are using the topics
=> Gcp Pubsub Gateway Quality of life Fixes

examples/event-sources/gcp-pubsub.yaml, gateways/community/gcp-pubsub/config.go, gateways/community/gcp-pubsub/start.go
The idea is to make it possible to subscribe to a topic in a different project by setting the `topicProjectID` field in the event source configuration. If the field isn't set, we continue to use the `projectID` field by default. We also still use the `projectID` field for the subscription.
Related issue: https://github.com/argoproj/argo-events/issues/329
=> Pub/Sub: multi-project support

sensors/trigger.go
Allows resource parameters to set/enforce a `metadata.namespace` for
externally sourced workflows. Prior to this change, doing so would
result in "failed to create resource object. err: the namespace of the
provided object does not match the namespace sent on the request"
errors.
=> Apply resource parameters before defaulting namespace

examples/event-sources/resource.yaml, gateways/core/resource/validate.go
The `namespace` field of a resource event source is now optional to
allow for configuration that would watch for resource related events in
all namespaces at once. Simply omitting the field works in this way
because the k8s dynamic client used in implementation can accept a
zero-length string for namespace.
=> Allow watching of resources in all namespaces at once

examples/event-sources/resource.yaml, gateways/core/resource/config.go, gateways/core/resource/config_test.go, gateways/core/resource/start.go, gateways/core/resource/start_test.go, gateways/core/resource/validate.go
This PR fixes the `Group` being removed whenever `Version` == `v1` and relates to #328 
In the issue, the API group `build.openshift.io/v1` was originally transformed to just `v1` which caused `Build` resource to be undetected.
Additional changes:
- Kubernetes core API group can now be denoted as empty string `""` and is therefore implicit if not provided
=> Fix missing resource group

hack/k8s/manifests/kustomization.yaml
When `argoproj/argo-events` is installed alongside `argoproj/argo` via Kustomize,
there is a collision between the workflow CRD defined by the argo project
and the one which is duplicated in this project. An example of this
issue in action would be a kustomization file which looks like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/argoproj/argo//manifests/cluster-install
- github.com/argoproj/argo-events//hack/k8s/manifests/
```
A `kustomize build` with that kustomization.yml results in the following error with kustomize v3.2.0:
```
Error: accumulating resources: recursed merging from path 'github.com/argoproj/argo-events//hack/k8s/manifests/': may not add resource with an already registered id: …
```
=> Omit duplicate CRD for workflows

sensors/trigger.go
Add nil check in nodeStatus created by sn.GetNodeByName to avoid panic when wrong dependency is selected
=> Event Sensor got panics if gateway not existed selected in dependency (#383)

hack/k8s/manifests/argo-events-cluster-roles.yaml
After installing argo-events into a cluster, it is convenient to have
anyone with the admin, edit, or view roles to be able to interact
with the sensors and gateways. A way to accomplish this is to create
a cluster role with the appropriate permissions, and aggregate them
to the respective cluster roles. Here is a link to the kubernetes doc:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
This is very similar to what is done for argo workflows, as seen here:https://github.com/argoproj/argo/blob/fc1ec1a51462c9a114417db801e3a9715d3dc6b4/manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml
This commit addresses the issue reported in #381
=> Aggregate gateway and sensor permissions to admin/edit/view roles

examples/event-sources/calendar.yaml
If a user wants to treat the `userPayload` as JSON, it should be define as JSON not as a string.
=> chore: Fix Calendar userPayload JSON Example

examples/event-sources/resource.yaml
Accorinding to https://github.com/argoproj/argo-events/blob/master/pkg/apis/eventsources/v1alpha1/types.go#L119, the only types for `type` are `ADD`, `DELETE`, and `UPDATE`. I assumed `MODIFIED` is suppose to be `UPDATE`
=> fix: Resource Event Source Example

examples/event-sources/gcp-pubsub.yaml, examples/gateways/gcp-pubsub.yaml
Eventsource type is `pubsub` not `gcp-pubsub` also properties for a pubsub in the eventsource spec should be `pubSub` not `pubsub`. Once I fixed those submitting a message to the topic caused the sensor to trigger and all the right stuff to happen.
It seems like both of these incorrect names should probably have created more noise in my logs. I didn't see any errors but I might not have been looking in the right place. I can file an issue for that if you would like.
=> fix: gcp pubsub example

docs/tutorials/02-parameterization.md
Add `02-parameterization` in `example/tutorials` path
=> fix: Add missing path on tutorials

docs/installation.md
Helm 3 requires a name to be specified in the helm command or using the --generate-name flag. This PR adds a name arg to the `helm install` command.
=> docs(installation): adding name to helm command

examples/event-sources/aws-sns.yaml, examples/event-sources/github.yaml, examples/event-sources/gitlab.yaml, examples/event-sources/slack.yaml, examples/event-sources/storage-grid.yaml
Please let me know if I missed anything. This is intended to close #431 -- the EventSource documentation was missing the `method` key, which was causing 405 HTTP responses for things like Slack and GitHub webhooks.
=> docs: Add method attribute to all webhook-derived EventSource examples

docs/tutorials/01-introduction.md
For some reason, `create`ing the webhook sensor instead of `apply`ing it causes the following err:
```
error: error parsing https://github.com/argoproj/argo-events/tree/master/examples/sensors/webhook.yaml: error converting YAML to JSON: yaml: line 114: mapping values are not allowed in this context
```
In any case, I suggest we can prefer the idempotent `apply`.
=> docs: Use kubectl apply over kubectl create

gateways/server/aws-sns/start.go, gateways/server/aws-sqs/start.go, gateways/server/common/aws/aws.go, gateways/server/common/aws/aws_test.go, pkg/apis/eventsources/v1alpha1/types.go, sensors/triggers/aws-lambda/aws-lambda.go
This PR will fix #518. Added `roleARN` in SQS and SNS eventsource. Gateway will create the  AssumeRole Cred-Provider AWS session if the roleARN provided in the definition.
=> feat: Implemented Assume RoleARN for SQS and SNS

sensors/cmd/Dockerfile
Without it, error is seen as follows when trying to specify an git sourced trigger:
` error="failed to clone repository. err: exec: \"git\": executable file not found in $PATH"`
=> fix: Add git to Dockerfile yum packages for sensor image

api/event-source.html, api/event-source.md, api/gateway.html, api/gateway.md, api/sensor.html, api/sensor.md, examples/event-sources/aws-sqs.yaml, gateways/server/aws-sqs/start.go, pkg/apis/eventsources/v1alpha1/types.go
Added the ability to monitor AWS-SQS queues from a different AWS account. Make sure AWS access credentials have permissions to "GetQueueUrl", "ReceiveMessage", and "DeleteMessage" of cross-account Queue, and provide queue name and AWS Account Id in aws-sqs-event-source.
Closing issue #464
=> feat: add AWS-SQS cross account queue monitoring

examples/sensors/gitlab.yaml
This cause gitlab trigger failed when create pod
=> service account is neccessary when create a pod in 2.6.3

hack/k8s/manifests/argo-events-cluster-roles.yaml
Fix missing `EventSource`s RBAC aggregation.
This should allow `EventSource` CRDs to be accessed with the same required permissions as other Argo-Events resource types.
=> fix: RBAC EventSource aggregation

manifests/base/crds/eventsources-crd.yaml, manifests/base/crds/gateway-crd.yaml, manifests/base/crds/kustomization.yaml, manifests/base/crds/sensor-crd.yaml, manifests/base/kustomization.yaml, manifests/install.yaml, manifests/namespace-install.yaml
I was a bit reckless when upgrading CRD from `v1beta1` to `v1` in #607. I did two mistakes:
1. Simple versions (`version`) are no longer available, only the long form `versions` is supported
2. A `schema` field is a required in `v1`. That means, even enforcing `v1` api with an empty spec like this:
```
schema:
openAPIV3Schema:
type: object
```
would require users to create every object with `--validate=false` flag for now, and I don't think that's what we want.
Let's revert back to `v1beta1`.
Also.. fixing a typo `s/cdrs/crds/g` and making `event-source` CRD name consistent with `pkg/apis/eventsources/`
I've tried implementing the OpenAPIV3Schema in another PR https://github.com/argoproj/argo-events/pull/624, but I'm not much successful with that so far... Let's discuss that option there.
=> fix: Revert CRD apiVersion

examples/sensors/complete-trigger-parameterization.yaml
to be able to modify workflows namespace key in it's spec it needs to be indented at "Apply parameters for workflow resource fetched from the S3 bucket" and the path is "metadata.namespace"
=> docs: workflow namespace

api/event-source.html, api/event-source.md, api/gateway.html, api/gateway.md, api/openapi-spec/swagger.json, api/sensor.html, api/sensor.md, controllers/gateway/resource.go, controllers/sensor/resource.go, pkg/apis/gateway/v1alpha1/openapi_generated.go, pkg/apis/gateway/v1alpha1/types.go, pkg/apis/gateway/v1alpha1/zz_generated.deepcopy.go, pkg/apis/sensor/v1alpha1/openapi_generated.go, pkg/apis/sensor/v1alpha1/types.go, pkg/apis/sensor/v1alpha1/zz_generated.deepcopy.go
This PR makes both gateway and sensor controllers backward compatible with deprecated spec.
The old spec will be unsupported in few releases.
=> fix(controller): Make gateway and sensor controllers backward compatible

api/event-source.html, api/event-source.md, api/gateway.html, api/gateway.md, api/sensor.html, api/sensor.md, hack/api-docs-template/members.tpl, hack/api-docs-template/pkg.tpl, hack/api-docs-template/type.tpl, hack/update-api-docs.sh
Anyone who runs `make codegen` or `make api-docs` will regenerate the api-docs with different commit id in it, this is quite annoying.
Use updated templates, to remove commit id part from it.
Closes #614
=> chore: Remove commit id from generated api-docs. Closes #614

docs/installation.md
Hello,
On the **Installation** page, the **Step-by-Step Installation** section contains various `kubectl apply -f <manifest URL>` commands, some of which don't work because the URLs contain typos. This pull request corrects the broken URLs that I found.
Thanks!
=> docs: correcting broken links on 'installation' page

README.md, controllers/gateway/informer.go, controllers/gateway/resource.go, controllers/gateway/resource_test.go, controllers/sensor/informer.go, controllers/sensor/resource.go
The latest changes to gateway and sensor controller construct the deployment name as `<gateway-name>-<gateway-type>-gateway-<random-char>`, e.b. webhook-gateway-webhook-gateway-12345 which is not correct naming. We should not add `<gateway-type>-gateway` to the deployment or service name. Let the user decide what they want to call their gateway and sensor.
=> fix: gateway and sensor resource names

api/openapi-spec/swagger.json, api/sensor.html, api/sensor.md, pkg/apis/sensor/v1alpha1/openapi_generated.go, pkg/apis/sensor/v1alpha1/types.go, sensors/triggers/standard-k8s/starndard-k8s.go
This change enables the standard K8s trigger to use a live resource from the K8s cluster as artefact, instead of using the definition of `source`. 
A new option `liveObject` (of type `bool`) is introduced on the trigger template, and if set to true, the specified artefact is used to uniquely identify the resource to fetch from the cluster
```yaml
triggers:
- template:
name: webhook-pod-trigger
k8s:
group: apps
version: v1
resource: deployments
operation: update
liveObject: true
source:
resource:
apiVersion: apps/v1
kind: Deployment
metadata:
name: web-deployment
namespace: web
parameters:
- src:
dependencyName: test-dep
contextKey: time
dest: spec.template.metadata.annotations.events\.argoproj\.io/restartedAt
```
This will fetch the resource of type `deployment` in  `apps/v1` with the …
=> feat: Support for using a live K8s resource in standard K8s triggers

docs/triggers/k8s-object-trigger.md
if the name of Sensor is "webhook-sensor", the gate-way client cannot send request to the desired sensor, so the name should be changed into "webhook".
---
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
name: webhook
spec:
replica: 1
type: webhook
eventSourceRef:
name: webhook-event-source
template:
serviceAccountName: argo-events-sa
service:
ports:
- port: 12000
targetPort: 12000
subscribers:
http:
- "http://webhook-sensor.argo-events.svc:9300/"
```
The above code is for the `Gateway` which is introduced at [triggers/k8s-object-trigger page](https://argoproj.github.io/argo-events/triggers/k8s-object-trigger/)
That says the endpoint of subscriber is "http://webhook-sensor.argo-events.svc:9300/". That means the name of a `Sensor` should be `webhook` not `webhook-sensor`.
But …
=> fix: wrong name of Sensor

docs/index.md
:wave: noticed that the `Concepts` link in the index page linked to the wrong doc. Looks like it was renamed in 0220b694449d8ebd5cfc968216087361a3a92ff9. Thanks!
=> docs: Fix link to Concepts in index

docs/setup/github.md
```yaml
apiVersion: v1
kind: Secret
metadata:
name: github-access
type: Opaque
data:
access: <base64-encoded-api-token-from-previous-step>
```
[vs.](https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/github.yaml)
```yaml
...
apiToken:
name: github-access
key: token
...
```
=> fix(documentation): use secret key referred in eventsource

common/logger.go, controllers/sensor/config.go, go.mod
Closes #630 
Uses json log formatter if stdout is not a tty. This will make it a lot easier to view logs in a log ingestor. It should be noted that this mr will change the default log formatter to JSON. This is because a tty is not allocated when executing any of the binaries. Should there be a way to force the log format to text?
=> feat: Use json log formatter if stdout isnt tty

sensors/cmd/Dockerfile
Opening a PR to bump the version of Sensor docker image and also add a `yum update` to allow patching of the vulnerabilities present in a few of the installed packages. Bellow is a [trivy](https://github.com/aquasecurity/trivy) report executed against the latest sensor image from DockerHub: (all other argo images are vulnerability free as they're not based on Ubuntu)
`trivy --exit-code 0 --severity CRITICAL,HIGH,MEDIUM --ignore-unfixed argoproj/sensor:v0.16.0`
```2020-07-08T15:36:15.139+0200    INFO    Detecting RHEL/CentOS vulnerabilities...
argoproj/sensor:v0.16.0 (centos 7.6.1810)
=========================================
Total: 84 (UNKNOWN: 0, LOW: 0, MEDIUM: 53, HIGH: 31, CRITICAL: 0)
+--------------------+------------------+----------+-------------------+-------------------------+--- …
```
=> fix: Sensor Dockerfile is based on Ubuntu 7 which has a few vulnerabilities

examples/event-sources/gcp-pubsub.yaml
The example specified in gateway : https://github.com/argoproj/argo-events/blob/master/examples/gateways/gcp-pubsub.yaml has the secret mounted in /gcp-pubsub-creds-dir. Hence modifying the credentialsFile property to match it accordingly.
=> chore: modify credentialsFile to be in sync with gateway

eventbus/driver/driver.go, eventbus/driver/nats.go, eventbus/eventbus.go, eventsources/eventing.go, eventsources/sources/amqp/start.go, eventsources/sources/awssns/start.go, eventsources/sources/awssqs/start.go, eventsources/sources/azureeventshub/start.go, eventsources/sources/calendar/start.go, eventsources/sources/emitter/start.go, eventsources/sources/file/start.go, eventsources/sources/gcppubsub/start.go, eventsources/sources/github/start.go, eventsources/sources/gitlab/start.go, eventsources/sources/hdfs/start.go, eventsources/sources/kafka/start.go, eventsources/sources/minio/start.go, eventsources/sources/mqtt/start.go, eventsources/sources/nats/start.go, eventsources/sources/nsq/start.go, eventsources/sources/redis/start.go, eventsources/sources/slack/start.go, eventsources/sources/storagegrid/start.go, eventsources/sources/stripe/start.go, eventsources/sources/webhook/start.go, go.mod, sensors/listener.go, sensors/listener_test.go
1. Fixed a bug that `()` in sensor dependency expression was trimmed when converting group expr to dependency expr.
2. 2 layers of event bus auto reconnect: 
a. utilize NATS reconnect feature - for short term connection lost such as NATS POD crash
b. Extra Goroutins in eventsource and sensor service to auto reconnect - for long term connection lost
3. Code refactory to use `ctx.Done` instead of `stopCh`
=> fix(eventbus): NATS eventbus auto reconnect and code refactory

controllers/eventsource/cmd/main.go, controllers/eventsource/controller.go, controllers/eventsource/controller_test.go, controllers/eventsource/resource.go, controllers/eventsource/resource_test.go, controllers/eventsource/validate.go, controllers/eventsource/validate_test.go, controllers/sensor/cmd/main.go, controllers/sensor/controller.go, controllers/sensor/resource.go, eventbus/driver/mocks/Driver.go, eventsources/cmd/main.go, eventsources/eventing.go, eventsources/sources/resource/start.go, eventsources/sources/resource/start_test.go, eventsources/sources/resource/validate.go, eventsources/sources/resource/validate_test.go, go.mod, pkg/apis/common/common.go
1.  Use `recreate` strategy for some of the eventsources deployment update.
2. Now EventSource allows multiple types of sources defined in one spec, following the rules:
a.) **Event source with `rollingUpdate` and `recreate` are not allowed in one EventSource object** - Otherwise when the EventSource is updated, there will be downtime for those `rollingUpdate` type event sources such as `webhook`.
b.) **Event name (the map key) needs to be unique in one EventSource object, even different type of event source can not use same name** - Because we use EventSourceName and EventName in Sensor as dependency.
c.) `rollingUpdate` types use replicas defined in the spec, defaults to 1;
d.) `recreate` ignores replica field in the spec, it always uses `1`
3. **Added missing `Resource` type …
=> feat: Different deployment update strategy for different event sources

.gitattributes
Those files are auto-generated by `make codegen`, so their diffs should be minimized to make reviewers' life easier!
refs:
- How to mark files as "auto-generated": [Customizing how changed files appear on GitHub - GitHub Docs](https://docs.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github)
- How to confirm a file is marked as intended: [Git - git-check-attr Documentation](https://git-scm.com/docs/git-check-attr)
=> chore: mark some files as auto-generated

.github/ISSUE_TEMPLATE/bug_report.md
Currently, the bug report template requests information about OS and browser. I am not sure that information is useful. I think providing Kubernetes, argo, and argo-events versions would be more appropriate for bug reports.
=> chore: Change environment section in bug report template

sensors/triggers/argo-workflow/argo-workflow.go, sensors/triggers/standard-k8s/standar-k8s.go
Fixes #794
Added labels to all the created k8s objects including `workflow`
`events.argoproj.io/sensor: sensor-name`
`events.argoproj.io/trigger: trigger-name`
`events.argoproj.io/action-timestamp: timestamp`
=> fix(workflow-trigger): Add labels to created k8s objects. Fixes #794

sensors/listener.go
when lots of sensors got updated, eventbus connect is really unstable.
=> fix: retry when connect to eventbus in sensor

examples/sensors/trigger-source-git.yaml, store/git.go, store/url.go
Don't need to mount `~/.ssh/known_hosts` to the POD any more to pull resources from git with `git://xxxxx`.
Closes #841
=> feat: Connect to git with InsecureIgnoreHostKey. Closes #841

sensors/listener.go
Fixes #860
This pr ensures that a subscription exists as long as there's an active connection to the eventbus. 
- This was tested locally by installing argo-events and testing my dev sensor image.
- I started an instance of the webhook eventbus/sensor. Then I verified that events flowed to the sensor.
- I then deleted all of the nats eventbus pods to force close the connection `kubectl delete po -n argo-events -l 'eventbus-name=default'`
- Then i verified that the subscription was eventually re-established and events flow correctly
- I repeated the deletion steps to validate that it works multiple times
I couldn't find any tests that touch this area but i could've missed them?
=> fix: Add logic to ticker loop to ensure subscription always exists with an open connection

docs/tutorials/01-introduction.md
fix Inspect the event-source command
=> fix: tutorial-introduce typo fix

docs/eventsources/naming.md, docs/webhook-authentication.md, eventbus/driver/nats.go, eventsources/eventing.go
The change implemented an in-memory cache for acked message IDs, it is used to make sure acked IDs will not make any impact on the triggering.
Closes #850 
Closes #853
=> feat: Implemented Exact Once triggering for NATS event bus

api/event-source.html, api/event-source.md, api/openapi-spec/swagger.json, eventsources/sources/kafka/start.go, pkg/apis/eventsource/v1alpha1/generated.proto, pkg/apis/eventsource/v1alpha1/openapi_generated.go, pkg/apis/eventsource/v1alpha1/types.go
Extend kafka URL to support multiple brokers, separated by comma.
```
pec:
kafka:
example:
url: kafka1.argo-events:9092,kafka2.argo-events:9092
```
Closes #892
=> feat:  kafka multiple-broker support. Closes #892

docs/setup/github.md, docs/setup/gitlab.md
Checklist:
I take more time when my first setup GitLab event-source without the YAML example. But I found an event-sources tutorial. I think others have the same problem.
=> docs: Add GitHub and GitLab example event-source yaml.

common/retry.go, eventsources/eventing.go, sensors/listener.go
1. Retry initial EventBus connection;
2. Retry starting eventing servers;
3. Panic EventSource POD if there's no active eventing servers(failed after retry)
Checklist:
Closes #926
=> feat: Retry starting event server and quick fail. Closes #926

eventsources/sources/amqp/start.go
When connection/channel is closed, it keeps reading empty messages from the channel without checking if it's successful.
Checklist:
Fixes #920
=> fix(amqp): Return error when channel is closed. Fixes #920

examples/event-sources/mqtt.yaml
=> docs: Quote MQTT example correctly

docs/triggers/slack-trigger.md, examples/event-sources/mqtt.yaml
Checklist:
Resolves: https://github.com/argoproj/argo-events/issues/942
=> fix: documentation - Adding `channels:read` permission to Slack Trigger Documentation

controllers/sensor/validate.go, controllers/sensor/validate_test.go, examples/sensors/time-filter-webhook.yaml, sensors/dependencies/filter_test.go
=> feat: Validate dependencies duplication. Closes #971

eventsources/sources/resource/start.go
return entire event object instead of just event.obj
Signed-off-by: Scott Weitzner <scottweitzner@gmail.com>
Checklist:
=> fix(eventsource/resource): return entire event object instead of just event.obj

controllers/eventbus/cmd/main.go, controllers/eventbus/controller.go, controllers/eventbus/controller_test.go, controllers/eventsource/cmd/main.go, controllers/eventsource/controller.go, controllers/sensor/cmd/main.go, controllers/sensor/controller.go, manifests/base/crds/argoproj.io_eventbus.yaml, manifests/base/crds/argoproj.io_eventsources.yaml, manifests/base/crds/argoproj.io_sensors.yaml, manifests/cluster-install/rbac/argo-events-aggregate-to-admin.yaml, manifests/cluster-install/rbac/argo-events-aggregate-to-edit.yaml, manifests/cluster-install/rbac/argo-events-aggregate-to-view.yaml, manifests/cluster-install/rbac/argo-events-cluster-role.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/namespace-install/rbac/argo-events-role.yaml, pkg/apis/eventbus/v1alpha1/generated.proto, pkg/apis/eventbus/v1alpha1/types.go, pkg/apis/eventsource/v1alpha1/generated.proto, pkg/apis/eventsource/v1alpha1/types.go, pkg/apis/sensor/v1alpha1/generated.proto, pkg/apis/sensor/v1alpha1/types.go
Checklist:
Closes #1029
This PR:
1. Enabled `status` subresource for CRDs, and controllers use `status` update API to update object status;
2. Controllers do not watch `status` change any more;
3. Fixed a bug that it kept emitting UPDATE notifications and updating status field infinitely.
4. Some code refactory and enhancement.
=> feat: use status resources for controller reconciliation. Closes #1029

controllers/eventbus/installer/nats.go, controllers/eventbus/installer/nats_test.go
Checklist:
Fixes #1026
Old config:
```
http: 8222
include ./auth.conf
cluster {
port: 6222
routes [
nats://eventbus-default-stan-svc:6222
]
cluster_advertise: $CLUSTER_ADVERTISE
connect_retries: 10
}
streaming {
xxxxxx
}
```
New config:
```
http: 8222
include ./auth.conf
cluster {
port: 6222
routes: [
nats://eventbus-default-stan-0.eventbus-default-stan-svc.argo-events.svc:6222,nats://eventbus-default-stan-1.eventbus-default-stan-svc.argo-events.svc:6222,nats://eventbus-default-stan-2.eventbus-default-stan-svc.argo-events.svc:6222
]
cluster_advertise: $CLUSTER_ADVERTISE
connect_retries: 10
}
streaming {
xxxxx
}
```
Tested in a real environment, `routes` change in the configmap will be gradually picked up when the NATS pods restart, and there's …
=> fix(eventbus): set nats routes with pod DNS names. Fixes #1026

sensors/triggers/slack/slack.go
=> fix: 1028 - Not able to send message to slack private channel

hack/update-codegen.sh, pkg/client/eventbus/clientset/versioned/typed/eventbus/v1alpha1/eventbus.go, pkg/client/eventbus/clientset/versioned/typed/eventbus/v1alpha1/eventbus_client.go, pkg/client/eventbus/clientset/versioned/typed/eventbus/v1alpha1/fake/fake_eventbus.go, pkg/client/eventbus/clientset/versioned/typed/eventbus/v1alpha1/fake/fake_eventbus_client.go, pkg/client/eventbus/informers/externalversions/eventbus/v1alpha1/eventbus.go, pkg/client/eventbus/informers/externalversions/eventbus/v1alpha1/interface.go, pkg/client/eventbus/informers/externalversions/generic.go, pkg/client/eventbus/listers/eventbus/v1alpha1/eventbus.go
With k8s version upgraded to v1.9.6, `code-generator` was also upgraded to new version, which broke the original codegen patch for `EventBus` plural (We want `EventBus` instead of `EventBuses`). This PR permanently fixes the issue.
Checklist:
=> fix(codegen): EventBus codegen plural issue introduced by k8s upgrade

sensors/triggers/slack/slack.go
Fixes #1057  The iteration should not assume every page has size of limit set (200)
Checklist:
=> fix(slack trigger): properly iterate api response

Dockerfile, eventsources/eventing.go, sensors/listener.go
=> fix: Use different clientID for each EventBus reconnection. Fixes #1055

docs/validating-admission-webhook.md, mkdocs.yml
=> fix(docs): fix validating webhook installation url

controllers/eventbus/cmd/main.go, controllers/eventbus/controller.go, controllers/eventbus/installer/exotic_nats.go, controllers/eventbus/installer/exotic_nats_test.go, controllers/eventbus/installer/installer.go, controllers/eventbus/installer/installer_test.go, controllers/eventbus/installer/nats.go, controllers/eventbus/installer/nats_test.go, controllers/eventsource/cmd/main.go, controllers/sensor/cmd/main.go
=> feat: Prevent EventBus with clients connected from being deleted

sensors/triggers/slack/slack.go
=> fix: 1077 - JoinConversation for private channel throws method_not_supported_for_channel_type

eventsources/sources/github/hook_util.go, eventsources/sources/github/hook_util_test.go
Fix the bugs mentioned in https://github.com/argoproj/argo-events/issues/1112.
Function `sliceEqual` is used to compare the Github events listed in the spec and the ones from Github API response.
It should:
1. If "*" (`all_events`) is in both slices, that should be considered as equal.
2. It should compare ignoring the duplicate and order, which means `{"a", "c", "a", "b"}` = `{"b", "c", "c", "a"}` = `{"a", "b", "c"}`
Checklist:
=> fix(GithubEventSource): Compare events ignoring order and duplicate

docs/tutorials/07-filters.md
Signed-off-by: Tim Collins <tim@thecollins.team>
Checklist:
=> docs: Enhance the filters tutorial for #1097

sensors/artifacts/git.go
We've run into an issue with using the existing git sensor with our repository.  The sensor works for a while until it starts erroring on `failed to fetch. err: some refs were not updated`.  This seems to happen when we merge code to our repository, and our deploy process updates tags.  Updating tags on existing branches causes git to throw an error unless you force fetch.  The artifact already force fetches when given a particular ref, and I can't think of a downside of doing it everywhere given that you wouldn't be making local changes to branches in a sensor.
Fixes: #1120
Checklist:
=> fix(git-sensor): force fetch from git repository

eventsources/sources/resource/start.go, test/e2e/fixtures/e2e_suite.go, test/e2e/fixtures/given.go, test/e2e/functional_test.go, test/e2e/testdata/es-resource.yaml, test/e2e/testdata/sensor-resource.yaml
When using Resource event source to watch UPDATE/DELETE events, the time used to filter the events (`afterStart`) should be event happen time instead of obj create time.
Checklist:
=> fix(resource-eventsource): Use event time instead of obj create time to filter UPDATE/DELETE events

Makefile
On release branch, the image tags in the manifests are not `latest` but the real version like `v1.3.0`, this makes `make start` fail like https://github.com/argoproj/argo-events/runs/2272839939?check_suite_focus=true. This PR is used to fix this issue.
Checklist:
=> chore: fix e2e ci build on release branch

docs/tutorials/02-parameterization.md
The link to the first page of the tutorial was wrong. An underscore instead of a dash after 01. 
This change repairs that error.
Checklist:
=> fix(docs): Update link in 02-parameterization.md

README.md
I discussed with @alexmt and he's going to reuse the existing link with instructions to join the CNCF workspace and channels. See https://github.com/argoproj/argo-cd/pull/6044#discussion_r614325390 for more context. Reverting previous change.
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
This reverts commit bb1f7407f5bcdd8362a73391eb7edec5129eb857.
Checklist:
=> docs: Revert "docs: Update link to the new CNCF Slack channel (#1179)"

controllers/eventsource/resource.go, controllers/eventsource/resource_test.go, controllers/sensor/resource.go, controllers/sensor/resource_test.go
Fix the issue that volume `emptyDir` is not mounted when EventBus auth is `None`.
Fixes #1194
Checklist:
=> fix: Always mount tmp emptyDir. Fixes #1194

docs/FAQ.md
I think it would be helpful to add this to the FAQ guide. The eventSourceName and eventName can be confusing at first.
=> docs(argo-events): Added helpful information to FAQ

eventsources/common/webhook/webhook.go
The `EventSource` logs contain noise in the form of duplicate properties
- `eventName`
- `eventSourceName`
E.g.
```json
{
"eventSourceName": "jp-webhook",
"eventSourceName": "jp-webhook",
"eventSourceType": "webhook",
"eventName": "example",
"eventName": "example"
}
```
The following are the original contiguous logs:
```json
{"level":"info","ts":1621930364.5526974,"logger":"argo-events.eventsource","caller":"driver/nats.go:96","msg":"NATS auth strategy: None","eventSourceName":"jp-webhook","clientID":"client-jp-webhook-eventsource-6zw95-6c7794fcf8-6wsqb-507"},
{"level":"info","ts":1621930364.556608,"logger":"argo-events.eventsource","caller":"driver/nats.go:105","msg":"Connected to NATS server.","eventSourceName":"jp-webhook","clientID":"client-jp-webhook-eventsource-6zw95-6c7794fcf8-6wsqb …
```
=> chore: remove source of duplicate properties in JSON log

.github/workflows/release.yml, Dockerfile, Makefile
=> fix(ci): release action

docs/tutorials/03-trigger-sources.md
Replace broken link
Checklist:
=> docs: Update 03-trigger-sources.md

controllers/sensor/validate.go, controllers/sensor/validate_test.go
=> fix: duplicate trigger name validation. Fixes #1262

docs/tutorials/06-trigger-conditions.md
docs: Update 06-trigger-conditions.md
The last line seems unfinished, and missed a verb between "should following".  Proposed to change it from "You should following output, " to "You should get the following output." .
Checklist:
=> docs: Update 06-trigger-conditions.md

Makefile
Since Kubernetes v1.14, kustomize became a subcommand in kubectl so we can just use kubectl instead.
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
Checklist:
=> build: Switch to use kustomize subcommand in kubectl

sensors/triggers/argo-workflow/argo-workflow.go
The field name `generatedName` in the error of argo_workflow trigger is wrong. The correct name is `generateName`.
ref: https://github.com/kubernetes/apimachinery/blob/02cfb53916346d085a6c6c7c66f882e3c6b0eca6/pkg/apis/meta/v1/unstructured/unstructured.go#L258
Checklist:
=> fix(trigger): correct field name in error message

docs/service-accounts.md
the instructions link in "Service Account for Trigged Workflows" section is broken. Find the correct one ,and replaced it.
Checklist:
=> docs: fix broken link

docs/eventsources/gcp-pubsub.md, eventsources/sources/gcppubsub/start.go, examples/event-sources/gcp-pubsub.yaml
The rest of my application runs locally and uses the PubSub emulator, and I'd like to be able to run Argo Events locally as well.
My application triggers Argo Workflows via the GCP PubSub event source. However, when pointing the PubSub source at the emulator (by setting the `PUBSUB_EMULATOR_HOST` environment variable), the source errors out on the permissions test, since the PubSub emulator doesn't support that gRPC call.
This PR makes the GCP PubSub event source skip the permissions check when the `PUBSUB_EMULATOR_HOST` environment variable is set.
I've tested this locally on my machine, and events are being pulled from the PubSub emulator with these changes.
=> feat: support for PubSub emulator

docs/eventsources/setup/github.md
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> docs: Add missing webhook secret key used for GitHub EventSource

examples/tutorials/03-trigger-sources/sensor-git.yaml
The tutorial on [git triggers ](https://argoproj.github.io/argo-events/tutorials/03-trigger-sources/) references this yaml file which contains the following:
>        source:
>             git:
>               url: "git@github.com:argoproj/argo.git"
>               cloneDirectory: "/git/argoproj"
>               sshKeyPath: "/secret/key"
>               namespace: argo-events
>               filePath: "examples/hello-world.yaml"
>               branch: "master"
The url is incorrect and causes an error when Argo Events attempts to utilize this workflow. This small change corrects that url to the yaml file I believe is being specified in the argo-workflows repo.
--- 
- updated git repo to point to the correct argo-workflows repo containing the specified hello-world.yaml file
Signed-off-by: …
=> docs: updated git url to point to the correct argo-workflows repo containing the specified hello-world.yaml file

sensors/listener.go, sensors/listener_test.go
Fixes: #1339
The `bool expression simplifier` is used by the Sensor to simplify and group different trigger conditions, fox example, `a || (a && b) || c` will be simplified as `a || c`, so that different triggers using same condition will only start one subscription to NATS Streaming. It's implemented by using [Quine–McCluskey](https://en.wikipedia.org/wiki/Quine%E2%80%93McCluskey_algorithm) algorithm. However, this implementation consumes huge memory when the number of the items involved in the bool expression is greater than certain number (around 20).
It's not easy to enhance the algorithm, so I'd like to disable it.
Possible impact:
1. There's no feature changes for the user;
2. It might start more subscriptions to STAN than before in some …
=> fix: disable bool simplifier due to performance issue. Fixes #1339

eventsources/sources/resource/start.go
Checklist:
This fixes spurious update events for k8s resources that have not changed at all. At the moment, those unwanted and unnecessary update events are generated by the apiserver dropping the watch at some point every 30 to 60 minutes. Obviously, having a downstream service relying on this behavior would be "weird" at best.
=> fix: resource eventsource duplicate update events. Fixes #760 (#1025)

mkdocs.yml
The tracking was being attributed to Argo CD, not Argo Events.
=> docs: Set-up Google Analytics tracking

api/event-source.html, api/event-source.md, api/jsonschema/schema.json, api/openapi-spec/swagger.json, pkg/apis/eventsource/v1alpha1/generated.proto, pkg/apis/eventsource/v1alpha1/openapi_generated.go, pkg/apis/eventsource/v1alpha1/types.go
=> fix: Marked optional fields in github and calendar eventsources

docs/eventsources/services.md
Currently, there's only documentation on the use of `service` in event source spec. Adding this example so that users don't have to search for the selector key for event source pods.
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
Checklist:
=> docs: Add example service that selects event source pods with selector

eventsources/sources/minio/start.go
Fixes #1396 
I'm not entirely sure why this line was there in the first place. But it blocks the goroutine when the `ListenBucketNotification` call returns (e.g. when minio is down).
=> don't wait for context when listening fails

go.mod, go.sum, sensors/triggers/triggers.go, sensors/triggers/triggers_test.go
=> fix: Creation of ingress resource with k8s trigger

eventsources/sources/pulsar/start.go
Currently consumed messages are not acknowledged by argo-events so pulsar keeps them around. This results in the whole queue flooding in when the pulsar eventsource is restarted.
Consumers should acknowledge all messages consumed. https://pulsar.apache.org/docs/en/concepts-messaging/#acknowledgement
This pull request sends acknowledgement to pulsar if the eventsource could handle the message successfully and send it to the eventbus.
Checklist:
=> fix: Ack handled messages in pulsar eventsource

api/event-source.html, api/event-source.md, api/jsonschema/schema.json, api/openapi-spec/swagger.json, pkg/apis/eventsource/v1alpha1/generated.proto, pkg/apis/eventsource/v1alpha1/openapi_generated.go, pkg/apis/eventsource/v1alpha1/types.go
Fixes the following JSON schema validation error when using `projects` field instead of the deprecated `projectID` field in a Gitlab Eventsource:
=> Modified deprecated projectID field of Gitlab Eventsource to be optional

.golangci.yml, Makefile, eventsources/sources/amqp/start.go, eventsources/sources/amqp/start_test.go, eventsources/sources/kafka/start.go, sensors/dependencies/filter_test.go, test/stress/main.go
This commit updates golangci-lint and removes the interfacer check because it
was marked as deprecated and will be removed. See
https://github.com/golangci/golangci-lint/issues/541 for more information.
Signed-off-by: William Van Hevelingen <william.vanhevelingen@acquia.com>
Checklist:
=> chore: Update golangci-lint to 1.44.0

test/e2e/fixtures/e2e_suite.go
adding a default location to look for .kube/config in home directory if the environment variable isn't defined
=> feat: add a default location to look for .kube/config in home directory

eventsources/sources/awssns/start.go, eventsources/sources/awssns/start_test.go
Given the SigningCertURL is part of the HTTP request body, I don't see where we're validating that the cert URL is indeed valid and from AWS before retrieving the cert [here](https://github.com/argoproj/argo-events/blob/master/eventsources/sources/awssns/start.go#L294). [Here's](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs#L244) an example of this being done in the .net SDK but I don't see that happening in the Golang SDK anywhere.
This PR adds that validation check explicitly.
Checklist:
=> fix: adds SigningCertURL validation for SNS messages

hack/crdgen.sh
This PR:
- Ignores the error from the event buses crd not existing if it doesn't already exist
- Closes #1638
Signed-off-by: J.P. Zivalich <jp@pipekit.io>
Checklist:
=> fix: Ignore mv event buses error on make codegen. Fixes #1638

controllers/sensor/validate.go, docs/sensors/triggers/argo-workflow.md, pkg/apis/sensor/v1alpha1/types.go, sensors/triggers/argo-workflow/argo-workflow.go
Closes #1647 
I haven't added any tests as was done in https://github.com/argoproj/argo-events/pull/1268. Looks like some refactoring would be required in order to unit test this (injecting command runner or something).
=> Adds argo stop as a supported operation for argoWorkflow triggers.

.github/dependabot.yml
Checklist:
@alexec is okay with allowing two prs now.
=> chore: Allow dependabot to open two prs

common/expr/eval_test.go, eventsources/eventing.go
Signed-off-by: Dillen Padhiar <dpadhiar99@gmail.com>
Fixes #1667 
Previously, expressions were filtered to replace `-` with `_` similar to how params for their keys of their pairs. However this causes unintended behavior and makes filters fail on messages which it shouldn't. 
Example yaml from issue:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
name: kafka-eventsource-test
spec:
kafka:  
my-test-event:
[...]
expression: "(body.someUUIDfield == '7e577e57-7e57-7e57-7e57-7e577e577e57')"
```
Sample JSON message:
```
{"someUUIDfield": "7e577e57-7e57-7e57-7e57-7e577e577e57",
"id": 1}
```
We expect this message to be published since it will evaluate true with our expression.
Logs for this message being sent:
```
2022-02-24T18:14:12.584Z        INFO    argo-events.eventsource …
```
=> fix: remove string replacement on expressions for event filtering

sensors/triggers/kafka/kafka.go
Checklist:
This tiny PR is to fix this [issue](https://github.com/argoproj/argo-events/issues/1656). The kafka async producer's error channel must be read otherwise the producer will be blocked. This case happened, e.g., when the brokers restarted.
=> fix: read kafka error channel. Fixes #1656

eventbus/driver/nats.go
=> fix: changing lastResetTime to a time.Time from int64 seconds so time comparison can occur at a finer granularity

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile
=> build: Make `make lint` faster

Makefile
=> fix: address timeout issue on CI server for 'make lint'

controllers/eventbus/validate.go, webhook/validator/eventbus.go
Fixes #1793 
User should not be able to change Jetstream StreamConfig, since once it's been used the stream settings have been passed to Jetstream
Checklist:
=> feat: User should not be able to change Jetstream StreamConfig

controllers/sensor/controller.go, controllers/sensor/resource.go, controllers/sensor/resource_test.go, controllers/sensor/validate.go, controllers/sensor/validate_test.go, webhook/validator/sensor.go, webhook/validator/sensor_test.go
Jetstream and STAN have diverged in terms of what they allow for dependencies being allowed to refer to the same Event. Therefore, the Admission webhook and Sensor Controller both need to grab the currently running EventBus spec to find out which one is. 
Checklist:
=> feat: Jetstream allows multiple dependencies to refer to the same Event

controllers/sensor/validate.go, docs/sensors/triggers/argo-workflow.md, examples/sensors/specia-workflow-trigger-submit-existing.yml, pkg/apis/sensor/v1alpha1/types.go, sensors/triggers/argo-workflow/argo-workflow.go
This PR fixes #1908 
This PR adds the feature about to submit from existing resources to the argo workflow trigger.
Specify the resource by adding "from" in "metadata" as shown below. In this example, `argo submit --from cronwf/special-trigger` is executed.
```
resource:
apiVersion: argoproj.io/v1alpha1
metadata:
name: special-trigger
from: cronwf
````
I propose this format as a first step. Please give me your comments.
(I tried to add tests, but the existing tests seemed to be hard-coded and adding test makes massive changes. So I don't added any test)
Checklist:
=> feat: add support of submit from existing resource (#1908)

sensors/artifacts/git.go
=> fix: git artifactory arbitrary file read issue

eventsources/sources/github/start.go
Fixes https://github.com/argoproj/argo-events/issues/1929
Checklist:
=> fix: Limit github hooks manager daemon lifetime to 10 min

DEPENDENCIES.md, api/event-source.html, api/event-source.md, api/jsonschema/schema.json, api/openapi-spec/swagger.json, eventsources/sources/amqp/start.go, go.mod, go.sum, pkg/apis/eventsource/v1alpha1/generated.proto, pkg/apis/eventsource/v1alpha1/openapi_generated.go, pkg/apis/eventsource/v1alpha1/types.go
The [`github.com/streadway/amqp`](https://github.com/streadway/amqp) library is no longer actively maintained. The new libary is now maintained by the RabbitMQ core team under a different package name [`github.com/rabbitmq/amqp091-go`](https://github.com/rabbitmq/amqp091-go).
Checklist:
=> chore: move from `streadway/amqp` to `rabbitmq/amqp091-go`

docs/eventsources/setup/gcp-pub-sub.md, docs/eventsources/setup/redis-streams.md, docs/sensors/filters/ctx.md, docs/sensors/filters/data.md, docs/sensors/filters/expr.md, docs/sensors/filters/script.md, docs/sensors/filters/time.md
I found some broken markdowns and have fixed them.
- https://argoproj.github.io/argo-events/eventsources/setup/gcp-pub-sub/#setup
- https://argoproj.github.io/argo-events/eventsources/setup/redis-streams/#event-structure
- https://argoproj.github.io/argo-events/sensors/filters/expr/#practical-example
- https://argoproj.github.io/argo-events/sensors/filters/data/#practical-examples-comparator
- https://argoproj.github.io/argo-events/sensors/filters/script/#practical-example
- https://argoproj.github.io/argo-events/sensors/filters/ctx/#practical-example
- https://argoproj.github.io/argo-events/sensors/filters/time/#practical-example
Checklist:
=> Fixed some broken markdowns

eventsources/sources/awssns/start.go, eventsources/sources/bitbucket/start.go, eventsources/sources/bitbucketserver/start.go, eventsources/sources/gitlab/start.go, eventsources/sources/storagegrid/start.go, eventsources/sources/stripe/start.go, eventsources/sources/webhook/start.go, sensors/artifacts/s3.go, sensors/artifacts/url.go
All the function `io.ReadAll()` invoked in Argo Events have ratelimit, which is around 65536, this is not enough for some of the use cases. This PR increases the limit for different cases.
Checklist:
=> chore: increase io.ReadAll size limit for variable use cases

common/scram_client.go, eventsources/sources/kafka/start.go, sensors/triggers/kafka/kafka.go
Checked this change in our deployment against properly configured Kafka cluster, and it actually fixes argoproj#2087.
Have no idea how to check this configuration issue in unit tests, so didn't touch them in the PR.
=> fix: add SCRAM support in Kafka triggers

controllers/cmd/start.go, controllers/config.go, pkg/apis/eventsource/v1alpha1/webhook_context.go
=> fix: added controller config validation

Makefile
I found that image-linux-arm64 only invoked dist/argo-events-linux-arm64 if this were changed to %. (Also, note it's similar to line 51 that way.)
Checklist:
=> fix: dependency should use %

examples/rbac/workflow-rbac.yaml
=> fix: Emissary executor reads and writes to WorkflowTaskResults, not Pods

examples/sensors/github.yaml
This PR fixes the github sensor example, there was a typo on X-Github-Event (capital H), plus it's in the header part instead of the body one
Cheers
=> [examples] fix filter for github sensor example

.github/workflows/ci.yaml, Makefile, webhook/webhook_test.go
Pinning the image to older version appears to stabilize the e2e tests
=> ci: Pin k3d to use rancher/k3s:v1.21.7-k3s1

docs/sensors/filters/expr.md
In other examples on this page and all of the examples in examples/sensors the top level property of the Expr filter is `exprs`, not `expr`. This is the list of the filters, not the one with the details (that's correctly `expr`).
The actual definition showing `exprs` appears to be here: https://github.com/argoproj/argo-events/blob/a9b5dd79c7341be999a526aacb77c87f7f7b3c08/pkg/apis/sensor/v1alpha1/generated.proto#L277
Here's some use in the examples showing `exprs` as opposed to `expr`. https://github.com/argoproj/argo-events/blob/b963de5607466a94bdc631d4f470d92913882178/examples/sensors/filter-with-multiple-filters.yaml#L25
Checklist:
=> Property name typo in Expr filter documentation

examples/event-sources/github.yaml
Update github EventSource example, added githubApp auth example
Signed-off-by: mike-serchenia <michael_serchenia@epam.com>
Checklist:
=> chore: EventSource example, added githubApp auth

docs/installation.md
Checklist:
Fix the service account name which will be granted 'anyuid' scc.
Tested on OpenShift 4.11.5
=> docs: fix service account name in OpenShift install

docs/sensors/filters/ctx.md
Fixes a bug in the context filter documentation (#2276)
=> fix(docs): context filter documentation

examples/sensors/filter-with-expressions.yaml, examples/sensors/filter-with-multiple-expr-filters-in-or.yaml
I've seen people struggling to understand what `fields.name` and `fields.path` are meant for. 
I hope the proposed examples will make it easier for everyone.
Checklist:
=> chore: Better examples for expr.fields

eventbus/jetstream/sensor/sensor_jetstream.go
Fixes #2278 
Use the existing key/value store if it already exists.
I tested this with the following experiments involving a webhook and a sensor with a trigger that is configured as "A&&B":
- start up new jetstream bus where key/value store doesn't already exist 
- use existing jetstream bus, send "A", modify jetstream version and `kubectl apply` it, send "B", verify trigger occurs
- use existing jetstream bus, send "A", delete sensor pod and see it restart, send "B", verify trigger occurs
=> fix: if key/value store already exists use that

controllers/eventbus/fuzz_test.go, go.mod, go.sum
Adds this fuzzer from cncf-fuzzng: https://github.com/cncf/cncf-fuzzing/blob/main/projects/argo/eventbus_controller_fuzzer.go
Signed-off-by: AdamKorcz <adam@adalogics.com>
Checklist:
=> eventbus controller: move fuzzer from cncf-fuzzing

examples/event-sources/gitlab.yaml
This example refers to GitLab usage, so I think this is a typo
=> fix: typo in gitlab example eventsource

.github/workflows/dependabot-reviewer.yml, README.md
Signed-off-by: Justin Marquis <34fathombelow@protonmail.com>
Part of #2250 
Use least permissive permissions by default on `.github/workflows/dependabot-reviewer.yml`.  Review job has proper permissions set.
Add Artifact Hub Badge.
Checklist:
=> chore: improve CLOMonitor score

USERS.md, sensors/dependencies/filter.go, sensors/dependencies/filter_test.go
Checklist:
This PR fixes a bug where when specifying only a subset of filters, in our case an expr filter and data filter, the filter would always evaluate to a 'pass'ing condition. 
This happens because the code doesn't check that we specified a filter before attempting to evaluate it, at which point it will default to `true`. 
The PR changes that behavior to check if the filter was `nil` before looking at what it evaluates to.
=> fix: fix bug in evaluation of filters with filtersLogicalOperator=or

docs/sensors/triggers/slack-trigger.md, examples/sensors/slack-trigger.yaml
Related issue: #1301 
This the follow-up PR for the newly added Slack trigger capabilities in #2369
=> docs: add new slack trigger capabilities to docs and examples

.github/workflows/release.yml
Signed-off-by: Justin Marquis <34fathombelow@protonmail.com>
fixed the output path for the sbom.
Checklist:
=> chore: fixed sbom output path

.github/workflows/release.yml
Signed-off-by: Justin Marquis <34fathombelow@protonmail.com>
Apparently the path for the download action should not contain the file name in it. :facepalm: 
Checklist:
=> chore: fixed sbom download path

cmd/commands/controller.go, common/common.go, common/logging/logger.go, controllers/cmd/start.go, controllers/eventbus/controller.go, controllers/eventbus/controller_test.go, controllers/eventbus/installer/installer.go, controllers/eventbus/installer/installer_test.go, controllers/eventbus/installer/nats.go, controllers/eventbus/installer/nats_test.go, go.mod, manifests/cluster-install/rbac/argo-events-cluster-role.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/namespace-install/rbac/argo-events-role.yaml
Resolves https://github.com/argoproj/argo-events/issues/2403
Currently, argo-events requires secrets list/watch/get privileges at a cluster scope. However, the only reason it wants this is to requeue the corresponding NATS eventbus to the eventbus controller's workqueue in case the NATS auth credentials secret becomes modified or deleted. The watch is largely unnecessary because:
* the secret will not naturally become modified or deleted. It is owned by the eventbus resource and not something a user manages.
* even if it does, it will eventually be reconciled by virtue of the eventbus sync interval
This change improves the security of argo-events by allowing Argo Events to run with only list/get secrets granted at a per-namespace basis (by allower users to create namespaced RoleBindings …
=> feat: allow granular secret privileges. additional controller logging/leader-election options

Makefile
docker buildx build started to generating [attestation manifests](https://docs.docker.com/build/attestations/attestation-storage/#attestation-manifest-descriptor) by default, which generates extra `unknown/unknown` manifests in the image artifactory. This makes `bom generate -i quay.io/argoproj/argo-events:xxxx` fail because `bom` does not recognize those manifests.
This PR disable the `docker buildx build` command generating attestation manifests to workaround the issue.
Checklist:
=> ci: disable docker build attestations

controllers/eventbus/installer/installer.go, controllers/eventbus/installer/jetstream.go, controllers/eventbus/installer/jetstream_test.go, manifests/base/controller-manager/controller-config.yaml, manifests/install.yaml, manifests/namespace-install.yaml
Fixes: https://github.com/argoproj/argo-events/issues/2452
Also updated supported JetStream EventBus version.
Checklist:
=> fix: remove the secret watch privilege dependency from js eb ctrler

.gitignore, common/common.go, common/leaderelection/leaderelection.go, common/leaderelection/leaderelection_test.go, common/leaderelection/test/auth.yaml, controllers/eventsource/resource.go, controllers/sensor/resource.go, docs/eventsources/ha.md, docs/sensors/ha.md, eventsources/cmd/start.go, eventsources/eventing.go, sensors/cmd/start.go, sensors/listener.go, test/e2e/functional_test.go, test/e2e/testdata/es-calendar-ha-k8s.yaml, test/e2e/testdata/sensor-log-ha-k8s.yaml
Implements optional kubernetes-based leader election. When an `EventSource` or `Sensor` opts in to kubernetes-based leader election, the Kubernetes lease resource will be used to coordinate pods. This change decouples the leader election mechanism from the `EventBus`. The default leaves an EventBus-based leader election mechanism in place.
The following annotation can be specified on either `EventSource` or `Sensor` to opt in to kubernetes-based leader election.
```yaml
annotations:
events.argoproj.io/leader-election: k8s
```
Checklist:
=> feat: Optional kubernetes-based leader election

controllers/eventbus/controller.go, controllers/eventsource/controller.go, controllers/sensor/controller.go
Controller-runtime client.Update() will mutate the object, which makes the following up Status.Update() do nothing - it didn't cause any issue because there are couple of reconciliations, eventually the Status gets updated correctly. 
Thanks @dfarr @bilalba for reporting the issue. 
Checklist:
=> fix(controller): use a copied object to update because of mutation

USERS.md, controllers/eventbus/installer/jetstream.go
When migrating from the NATS EventBus to the JetStream EventBus I noticed that the deployment was blocked by our admission controller as it requires certain labels to be present on the StatefulSets and Deployments.
It seemed that the EventBus controller only appends the labels from the EventBus CRD to the EventBus StatefulSet for the NATS EventBus and not for the JetStream EventBus, this PR adds this for JetStream EventBuses as well.
Checklist:
=> add labels to jetstream statefulset generated by eventbus controller

examples/sensors/github.yaml
Just fixing a booboo that tripped me up when implementing the github sensor.
=> fix github sensor example to use generateName

eventsources/common/naivewatcher/watcher_test.go
The naivewatcher test (specifically the `TestWatcherAutoCheck` test) exhibits nondeterministic behaviour. On occasion, the test will see unexpected file system events, causing the test to fail. Generally, there are two types of causes of failure:
1. Duplicate events
2. A remove+create event where we would expect to see a rename event
You can reproduce this locally by running (may take quite a few iterations before a failure occurs).
```
while true; do go clean -testcache && go test github.com/argoproj/argo-events/eventsources/common/naivewatcher; done
```
The issue appears to be due the way `watcher.Start` works, calling the `Check` function at a specified interval, and making timing issues possible. This fix tunes the parameters to make test failure less likely, I have not been able to …
=> chore: Reduce naivewatcher interval

.gitignore, docs/eventbus/kafka.md
Fix links for kafka eventbus docs.
Checklist:
=> fix(docs): kafka eventbus docs links

metrics/metrics.go
Checklist:
The golang metrics are not available from argo-events metrics repository. This PR add the default golang metrics to the repository.
=> feat: Add golang metrics to argo-events metrics registry.

common/expr/eval_test.go, common/retry_test.go
1. The `Convert2WaitBackoff` func converts `apicommon.Backoff` struct to a wait.Backoff struct used by the k8s.io/apimachinery/pkg/util/wait package. It extracts the fields from the input struct and converts them to the appropriate types for the output struct. Having a unit test for the `Convert2WaitBackoff` function is important to ensure that it converts the input `apicommon.Backoff` object to a `wait.Backoff` object with the correct values. The function has to parse and convert various fields, and the unit test verifies that the conversions are done correctly. 
2. The `removeConflicts` func removes any conflicting keys from a map. If there are two or more keys that share the same prefix, where one is a parent of the other, then the less-specific key is removed. This func is used in the …
=>  chore: adding tests for the removeConflicts function & the Convert2WaitBackoff function

eventbus/kafka/sensor/kafka_handler.go, eventbus/kafka/sensor/kafka_sensor.go, eventbus/kafka/sensor/trigger_handler.go
This is a bug fix for the Kafka EventBus. We discovered this bug through stress testing.
When a partition is unassigned from one consumer and assigned to a different consumer, we need to clear the trigger state. If we don't clear this state false trigger invocations can occur if a partition is reassigned back to a consumer that it was previously assigned to because stale messages will still be in memory.
**Example:**
Imagine a deployment with one replica and multiple triggers (but we can focus in on one trigger), where we have received an `a` event but are waiting on a `b` event.
| trigger | replica | condition | events |
| --- | --- | --- | --- |
| t1 | 1 | a && b | [a] | 
Later, we scale up our deployment to 2 replicas and a rebalance happens. The trigger (which maps to a partition) is …
=> fix(kafkaEventBus): Reset kafka consumer on cleanup

eventsources/common/fsevent/fileevent_test.go
1. `TestOpString:` This test verifies that the `Op.String()` function correctly converts an Op value to its corresponding string representation. It checks multiple values and compares the expected string representation with the actual result. 
2. `TestNewOp:` This test validates the `NewOp()` function, which converts a given string to an Op value. It tests different input strings representing Op values and compares the value with the actual result.
3. `TestEventString:` This test ensures the correctness of the `Event.String()` function, which returns a string representation of an Event. It checks diff Event instances with specific names and Op values, and validates that it is working properly.
We need test coverage to test the conversion/string representation functionality of the Op and …
=> chore: adding test coverage for file system events in argo-events

docs/installation.md
The webhook pod currently need to run with an admin user on openshift, we need to add the scc anyuid to the used user.
=> docs: add missing service account role for operator installation

USERS.md, controllers/eventbus/installer/jetstream.go
[#2657](https://github.com/argoproj/argo-events/issues/2657)
Current implementation of NATS eventbus assumes the cluster has 'cluster.local' domain defined, which not always the case.
Use cluster domain invariant service name - `evenbus-name.eventbus-namespace.svc` instead of `evenbus-name.eventbus-namespace.svc.cluster.local`
Checklist:
=> fix: use cluster domain neutral svc dns

Dockerfile
Upgrade Argo CLI to the latest version which is v3.4.8. Solves: #2581 
Basic functionality of the argo-workflows trigger was tested with various WorkflowTemplates, including new features that have been added since the old version we used, such as the 'expr' format in 'when' conditions as requested in the issue itself.
=> chore: upgrade Argo CLI version to v3.4.8

.github/CODEOWNERS
This ensures PRs get reviewers.  Currently they do not
removed due to not having write permissions on repo anymore (according to the CODEOWNERS file itself)
- @daniel-codefresh
- @dtaniwaki
=> chore: create .github/CODEOWNERS

examples/sensors/kafka-ttl.yaml
Why this PR: No example in `sensors` folder with the usage of `ttlStrategy`
Change I made: added `kafka-ttl` yaml file as an example on how to use `ttlStrategy`
=> chore: add kafka-ttl sensor example

eventbus/jetstream/eventsource/source_jetstream_test.go
Adding tests for `source_jetstream:`
`TestNewSourceJetstream:`
It checks that a new SourceJetstream instance is created without no errors.
It ensures that the EventSourceName field of the SourceJetstream instance is set correctly.
`TestSourceJetstream_Connect:`
It asserts sourceJetstream is not nil, letting us know that the creation of the SourceJetstream instance was successful.
It asserts that err is nil, indicating that no error occurred during the creation of the SourceJetstream instance.
It calls the Connect method on the sourceJetstream instance, passing the "test-client-id" as the clientID argument, and assigns the returned conn and err values.
`TestSourceJetstream_Initialize_Failure:`
This test case covers the failure scenario where the Initialize method encounters an error, …
=> chore: adding unit tests for source_jetstream

docs/tutorials/01-introduction.md
Fix #2737
Doc: Argo Workflow apply command link 404
=> Change to the link from the latest release of Argo Workflow
=> fix: Doc: Argo Workflow apply command link 404 #2737

api/event-source.html, api/event-source.md, api/jsonschema/schema.json, api/openapi-spec/swagger.json, common/saramaconfig.go, eventbus/kafka/base/kafka.go, eventbus/kafka/eventsource/source_conn.go, eventbus/kafka/eventsource/source_kafka.go, eventbus/kafka/sensor/kafka_handler.go, eventbus/kafka/sensor/kafka_sensor.go, eventbus/kafka/sensor/kafka_transaction.go, eventsources/sources/kafka/start.go, go.mod, go.sum, pkg/apis/eventsource/v1alpha1/generated.proto, pkg/apis/eventsource/v1alpha1/openapi_generated.go, pkg/apis/eventsource/v1alpha1/types.go, sensors/context.go, sensors/triggers/kafka/kafka.go, sensors/triggers/kafka/kafka_test.go
Note: the module path has changed to github.com/IBM/sarama since ownership transitioned away from Shopify
Fixes #2554
=> chore(deps): bump sarama to v1.41.2

go.mod, go.sum
This reverts commit 9c219e3c4fcf95bb44d9613949752ef5ffa7bf0b.
The author's [account is back](https://x.com/antonmedv/status/1711740187561033793?s=20) and I have confirmed with him personally that he's planning to keep the repo under `antonmedv/expr` going forward.
=> chore: Revert "fix: Replace antonmedv/expr with expr-lang/expr (#2850)"

CONTRIBUTING.md
Add a root CONTRIBUTING.md that directs to docs/CONTRIBUTING.md
- having a `CONTRIBUTING.md` at the root of the repo is a common convention
- I looked at the root of the repo initially, didn't find it, then checked the website, but potential contributors may think it doesn't exist as a result
Shamelessly copied from https://github.com/argoproj/argo-workflows/pull/10969 (thank you @agilgur5)
Checklist:
=> docs: add CONTRIBUTING.md at root of repo, directing to docs/

examples/event-sources/calendar.yaml
Fix typo `matadata` in calendar.yaml
=> Fix typo in calendar.yaml

eventbus/kafka/sensor/kafka_sensor.go
Checklist:
Fix issue https://github.com/argoproj/argo-events/issues/2958, added procuder.Errors() read and log to stop kafka sensor's producer from deadlocking.
=> fix: added Errors() read from kafkaSensor's producer

sensors/listener.go
Changing log level from `WARN` to `DEBUG` when events do not match a Sensor filter, as suggested by @whynowy in this [issue comment](https://github.com/argoproj/argo-events/issues/2672#issuecomment-1630131794). This represented ~400GB of logs per day in my cluster at scale, and logging the entire payload for discarded events is only useful for occasional debugging purposes.
=> fix: Reduce Sensor log verbosity for filtered events

sensors/listener.go
Checklist:
* [] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).
Fix the issue [#2928](https://github.com/argoproj/argo-events/issues/2928) that the trigger wasn't correctly retried as defined in the retryStrategy.
=> fix: fix trigger retryStrategy

docs/quick_start.md
The part of the command to replace the ARGO_WORKFLOWS_VERSION gets cut off, this adds a link for the user to grab a version from the Argo Workflow project as well as gives the user a quick link to find the latest version of Argo Workflows
Checklist:
* [ N/A] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).
=> Update quickstart with link to Argo Workflows versions, set as ENV VAR

common/leaderelection/leaderelection.go, common/viper.go, controllers/config.go, eventbus/driver.go, go.mod, go.sum
We have experienced an odd behaviour where argo-events would attempt to start the eventsource pod, then exit just a few seconds later without producing any meaningful error message. The process exit code was set to 1.
After some investigation and tracing the system calls, I found that the code responsible for this is related to usage of the `viper` config parsing library. Specifically, argo-events guards against bunch of possible errors while initially reading in the configuration, but does not have necessary error checking for setting up the file watchers. An example of such code can be found here:
https://github.com/argoproj/argo-events/blob/78d47a2b6e948b9a3fa3572f0c95d8dcf5d7d8ff/eventbus/driver.go#L151
viper's `WatchConfig()` method will attempt to setup a watcher and if it's …
=> fix logging on config watcher setup failure

eventsources/sources/azurequeuestorage/start.go
This should allow the Azure Queue Storage EventSource to decode base64-encoded queue messages properly and fix #3084 .
Checklist:
=> fix(AzureQueueStorage): update base64 encoding

metrics/metrics.go
=> feat: new Prometheus metrics build_info

USERS.md, eventsources/eventing.go
Checklist:
Adds a debug log in the EventSource which logs the incoming event body with the CloudEvents event ID for better correlation in the EventSource. Also adds the CloudEvents EventID to the `Failed to publish an event` log so we can actually know what event failed to publish to the EventBus. This ID was not available in that log before and when a failure occurred where the event failed to publish to the EventBus we were unable to pinpoint exactly what event failed to publish. This PR is meant to add more transparency to event failures in the EventSource so we have the ability to see what failed, similar to how we can debug the event in the Trigger.
=> Add more EventSource event logs for failed to publish events

eventsources/eventing.go
resolves [CloudEvent ID is too long - 72 chars](https://github.com/argoproj/argo-events/issues/3184#top) #3184
Checklist:
=> fix: CloudEvent.ID length to 32 chars

.gitignore, docs/metrics.md, metrics/metrics.go, sensors/listener.go
Signed-off-by: Taleb Zeghmi <talebz@zillowgroup.com>
To resolve [Prometheus metric for trigger exhaustion on retries #3185](https://github.com/argoproj/argo-events/issues/3185)
Checklist:
=> feat: argo_events_action_retries_failed_total metric

api/event-bus.html, api/event-bus.md, api/jsonschema/schema.json, api/openapi-spec/swagger.json, eventbus/jetstream/base/jetstream.go, manifests/base/controller-manager/controller-config.yaml, manifests/install.yaml, manifests/namespace-install.yaml, pkg/apis/eventbus/v1alpha1/generated.proto, pkg/apis/eventbus/v1alpha1/jetstream_eventbus.go, pkg/apis/eventbus/v1alpha1/openapi_generated.go
see **Allow Configurable Retention and Discard Policies for Jetstream EventBus** https://github.com/argoproj/argo-events/issues/3150.
Checklist:
=> feat: Jestream configurable DiscardNew policies

examples/tutorials/02-parameterization/sensor-05.yaml
Hi there!
Here are 2 small fixes for the tuto exemple `02-parameterization/sensor-05.yaml`:
- add one missing indent level for the `triggers.0.template.parameters.*` params
- fix for the 3 scr `dest: argoWorkflow.parameters.*` instead of `dest: k8t.parameters.*` 
---
Checklist:
=> Fix tuto exemple 02-parameterization/sensor-05.yaml

USERS.md, go.mod, go.sum
Checklist:
My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).
Bumps [github.com/aws/aws-sdk-go](https://github.com/aws/aws-sdk-go) from 1.44.209 to 1.47.11.
Minimum required version to support EKS Pod Identity authentication.  Fixes argoproj/argo-events#3039
=> chore(deps): bump github.com/aws/aws-sdk-go from v1.44.209 => v1.47.11

USERS.md, eventsources/sources/resource/start.go
Checklist:
Fixes #3238
This fix prevents argo-events from crashing when an unexpected, that is not a `*unstructured.Unstructured`, is encountered. The solution is to filter out those objects as they cannot be parsed and will not have information that can be used in the rest of process.
In the old situation argo-events would crash on receiving the unexpected object.
In the new situation argo-events will ignore the unexpected object.
In case that the object is indeed a `*unstructured.Unstructured`, the program will behave as it did before.
=> fix:eventsource crash on cast #3238

docs/sensors/triggers/build-your-own-trigger.md
Updating the link to proto file, it was moved and the link in the docs is currently invalid.
=> Update link to proto file in build-your-own-trigger.md

pkg/sensors/triggers/standard-k8s/standard-k8s.go
Fixes #3300 by adding some more commonly used cluster-scoped resources for manipulation by the kubernetes object trigger.
Checklist:
=> Add commonly used cluster-scoped resources to standard k8s trigger

Dockerfile
Just a small update to fix high rated CVE in Argo CLI
=> Upgrade Argo CLI version to v3.6.0 due to CVE-2024-27304

pkg/reconciler/eventbus/installer/assets/jetstream/nats-cluster.conf, pkg/reconciler/eventbus/installer/assets/jetstream/nats.conf
Fixes an issue where the EventBus fails to start if the JS_KEY environment variable begins with a number, causing the following error on startup:
> nats-server: variable reference for 'JS_KEY' on line 17 could not be parsed: Parse error on line 1: 'Expected a top-level value to end with a new line, comment or EOF, but got '1' instead.'
Fixes #3231
=> fix: wrap JS_KEY in quotes in nats-cluster.conf and nats.conf

pkg/eventsources/sources/awssns/fuzz_test.go, pkg/eventsources/sources/github/fuzz_test.go, pkg/eventsources/sources/slack/fuzz_test.go, pkg/eventsources/sources/stripe/fuzz_test.go, pkg/reconciler/eventsource/fuzz_test.go, pkg/reconciler/sensor/fuzz_test.go, pkg/sensors/triggers/fuzz_test.go
Checklist:
This moves over several of argo-events fuzz tests from [cncf-fuzzing](https://github.com/cncf/cncf-fuzzing/tree/main/projects/argo). These fuzz tests have been running for several years continuously on OSS-Fuzz, but due to recent refactoring in argo-events they broke. I have fixed the fuzz tests and rewritten them to native golang fuzzers (that use std libs fuzzing engine). Having them upstream will make maintenance much easier.
=> move fuzz tests upstream from cncf-fuzzing

pkg/sensors/triggers/custom-trigger/custom-trigger.go
`grpc.NewClient` does not automatically connect to the gRPC server anymore. This is unlike the previously used `grpc.Dial`[1].
This change reintroduces initial connection test.
[1]: https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md
I'm unsure whether we should actually do this, but at least it makes the code work again. 
fixes #3420.
Checklist:
=> fix: adjust connection for custom gRPC trigger

pkg/reconciler/sensor/fuzz_test.go, pkg/sensors/fuzz_test.go, pkg/sensors/triggers/argo-workflow/fuzz_test.go, pkg/shared/expr/fuzz_test.go
Checklist:
Moves more fuzzers in similar fashion as https://github.com/argoproj/argo-events/pull/3414
=> Move fuzzers upstream from cncf-fuzzing

USERS.md, pkg/eventbus/jetstream/sensor/trigger_conn.go
This PR fixes an issue in the error comparison to avoid log spew. Instead of comparing the errors directly, compare the string versions.
Checklist:
=> fix: compare errors with string to avoid log spew in jetstream sensor

pkg/eventsources/common/webhook/types.go, pkg/eventsources/common/webhook/webhook.go, pkg/eventsources/sources/awssns/start.go, pkg/eventsources/sources/bitbucket/start.go, pkg/eventsources/sources/bitbucketserver/start.go, pkg/eventsources/sources/gerrit/start.go, pkg/eventsources/sources/github/start.go, pkg/eventsources/sources/github/start_test.go, pkg/eventsources/sources/gitlab/start.go, pkg/eventsources/sources/slack/start.go, pkg/eventsources/sources/slack/start_test.go, pkg/eventsources/sources/storagegrid/start.go, pkg/eventsources/sources/storagegrid/start_test.go, pkg/eventsources/sources/stripe/start.go, pkg/eventsources/sources/webhook/start.go, pkg/eventsources/sources/webhook/start_test.go
Closes #3448 
We discovered an issue where the current argo-events webhook implementation will drop data when experiencing connectivity issues with NATS while still returning HTTP 200 status codes to the client. This breaks common webhook specifications including CloudEvent's and will result in catastrophic data loss for those who are using argo-events as a part of their core infrastructure.
This impacts all of the following EventSources:
- awssns
- bitbucket
- bitbucketserver
- github
- gitlab
- slack
- gerrit
- slack
- storagegrid
- stripe
- webhook
This PR introduces a few changes to address the immediate problem. The goal was to keep the changes as small as possible while also ensuring the problem is thoroughly addressed for all of the impacted EventSources.
1. Instead of using a …
=> Fix: catastrophic data loss on NATS connectivity issues

examples/tutorials/02-parameterization/sensor-05.yaml
Fix the trigger parameterization example from https://argoproj.github.io/argo-events/tutorials/02-parameterization/, as mentioned in #3432 and #3161.
The outer `parameters` section should be at template level, as defined in the Trigger spec (https://argoproj.github.io/argo-events/APIs/#argoproj.io/v1alpha1.Trigger). 
The other trigger parameterization example is configured correctly (https://github.com/argoproj/argo-events/blob/master/examples/sensors/complete-trigger-parameterization.yaml).
=> docs(sensor): move parameters to template level

docs/quick_start.md
Port-forward on svc/webhook-eventsource-svc instead of pod.
Checklist:
=> port-forward on svc/webhook-eventsource-svc 12000:12000 instead of pod.

.github/workflows/release.yml
ubuntu 20.02 [deprecated](https://github.com/actions/runner-images/issues/11101) -> latest (24.04)
Checklist:
=> chore: upgrade ubuntu runner

pkg/eventsources/sources/resource/start.go
Checklist:
Related with: https://github.com/argoproj/argo-events/issues/3494
This PR avoids nil pointer dereference when the event has no `Time` field.
Tested in kubernetes v1.30.10
=> fix: crash eventsource resource

pkg/shared/logging/logger.go
Closes: #3499
```
{"level":"info","ts":"2025-03-02T00:23:01.00458634Z","logger":"argo-events.sensor" xxxx
```
Checklist:
=> chore: use human readable time format in the log

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/APIs.md, pkg/apis/events/v1alpha1/eventsource_types.go, pkg/apis/events/v1alpha1/generated.proto, pkg/apis/events/v1alpha1/openapi_generated.go, pkg/eventsources/sources/gitlab/validate.go, pkg/eventsources/sources/gitlab/validate_test.go
This PR modifies the Gitab EventSource validation logic to allow configurations without `projects` or `groups`. This change ensures that users can manage webhooks externally while still using Argo Events.
- Removed the mandatory validation check for `projects` and `groups` in `validate.go`.
- Updated the test cases in `validate_test.go` to reflect the new behavior.
- Ran `go test -v ./pkg/eventsources/sources/gitlab/ -run TestValidateEventSource` successfully.
- Verified that Argo EventSource no longer requires projects/groups.
@ryancurrah
=> fix: allow gitlab eventsource to work without projects or groups

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/APIs.md, pkg/apis/events/openapi/openapi_generated.go, pkg/apis/events/v1alpha1/generated.proto, pkg/apis/events/v1alpha1/sensor_types.go
Checklist:
- Fix doc regarding strings being now handled as regexes, and not "as is" as it was in the past, in the sensors' data filters.
_As mentioned [in the sensors' filters documentation](https://github.com/argoproj/argo-events/blob/0a2ee96a61adb7f375e1628fa3ee59676daa5687/docs/sensors/filters/data.md?plain=1#L117) and [defined there in the code](https://github.com/argoproj/argo-events/blob/eb4bb0d1e9be5b76f30b3923640628ee853f7c0b/pkg/sensors/dependencies/filter.go#L361), and as I indeed observed, the string values can be regular expressions, and are in any case treated as regexes._
_The behaviour was introduced in [this PR](https://github.com/argoproj/argo-events/pull/396), but the associated comment was somehow changed back from “taken as regular expressions” to the initial “taken …
=> fix(doc): Update data filter doc about string handling
