argoproj/argo-events

- docs/quickstart.md
> Update docs/quickstart.md with more thorough instructions.

- signals/webhook/webhook_test.go
> fix-webhook-unit-test

- CHANGELOG.md
- docs/trigger-guide.md
Add info about inlined, file and url sources for trigger workflows in the docs as well as changelog.
Refs #41.
> Documentation updates.

- DEPENDENCIES.md
- Gopkg.lock
- Gopkg.toml
- cmd/sensor-controller/main.go
- controller/config.go
- controller/config_test.go
- controller/controller.go
- controller/controller_test.go
- controller/operator.go
- controller/signal.go
- controller/trigger.go
- sdk/micro_server.go
- signals/artifact/s3.go
- signals/calendar/calendar.go
- signals/resource/resource.go
- signals/stream/builtin/amqp/amqp.go
- signals/stream/builtin/kafka/kafka.go
- signals/stream/builtin/mqtt/mqtt.go
- signals/stream/builtin/nats/nats.go
- signals/webhook/micro/client/main.go
- signals/webhook/webhook.go
- store/file.go
- store/file_test.go
- store/inline.go
- store/s3.go
- store/store.go
- store/url.go
> switching to logrus logger

- CONTRIBUTING.md
- README.md
- docs/quickstart.md
> updating contributing and quickstart docs

- hack/k8s/manifests/sensor-crd.yaml
There's no field "description" in CustomResourceDefinition
> Fix the example CRD

- examples/gateways/storage-grid.yaml
- gateways/custom/storagegrid/Dockerfile
- gateways/custom/storagegrid/config.go
- gateways/custom/storagegrid/start.go
The functionality remains the same but the way routes are activated and deactivated is refactored
> Refactor storage grid gateway

- gateways/core/stream/amqp/config.go
- gateways/core/stream/amqp/start.go
- gateways/core/stream/kafka/config.go
- gateways/core/stream/kafka/start.go
- gateways/core/stream/mqtt/config.go
- gateways/core/stream/mqtt/start.go
- gateways/core/stream/nats/config.go
- gateways/core/stream/nats/start.go
- gateways/utils.go
> Added support for backoff option when making connections in stream gw

- CONTRIBUTING.md
https://github.com/argoproj/argo-events/commit/72fc6f2ffe71e0f8a7de0d5dedf4b836a79815f8#diff-018e220b50f876168d6d1d4dbf52ce84
> modify instalation link

- DEPENDENCIES.md
- Gopkg.toml
- Makefile
- examples/gateways/hdfs-configmap.yaml
- examples/gateways/hdfs.yaml
- examples/sensors/hdfs.yaml
- gateways/common/naivewatcher/event.go
- gateways/common/naivewatcher/mutex.go
- gateways/common/naivewatcher/watcher.go
- gateways/common/naivewatcher/watcher_test.go
- gateways/community/hdfs/Dockerfile
- gateways/community/hdfs/client.go
- gateways/community/hdfs/cmd/main.go
- gateways/community/hdfs/config.go
- gateways/community/hdfs/start.go
- gateways/community/hdfs/validate.go
- gateways/community/hdfs/validate_test.go
Resolve #142
I implemented the HDFS gateway.
I wasn't able to use [HDFS Inotify](http://hadoop.apache.org/docs/r3.2.0/api/org/apache/hadoop/hdfs/inotify/package-summary.html)  because it requires admin role and notifies everything happened in the cluster. Instead, I implemented naive file watcher which periodically scans the state of a watching directory and notify when the state is changed.
> Implement HDFS gateway

- README.md
> fix webhook sensor example

- store/creds.go
> fix(): trim white spaces in creds stored in k8s secret

- examples/sensors/file.yaml
- examples/sensors/hdfs.yaml
- gateways/common/fileevent/fileevent.go
- gateways/common/fsevent/fileevent.go
- gateways/common/naivewatcher/watcher.go
- gateways/common/naivewatcher/watcher_test.go
- gateways/community/hdfs/start.go
- gateways/community/hdfs/validate.go
- gateways/core/file/start.go
I made the payload of file and HDFS gateways json and usable in sensors.
> Improve file gateway

- Gopkg.lock
- Gopkg.toml
- gateways/community/github/config.go
- gateways/community/github/start.go
Add baseURL and uploadURL options: This allows using the gateway with github enterprise.
Also some further fixes to make this work with GHE. Can't say if this was working with regular GH without them.
> gateway/github: Enterprise support and some fixes

- controllers/gateway/operator_test.go
- controllers/sensor/operator_test.go
I'm trying to fix the tests, which fail in CI but succeed in my local environment.
> Fix operator tests

- gateways/community/github/start.go
- gateways/community/github/start_test.go
> github-gateway: Add delivery headers

- gateways/community/github/start.go
fix https://github.com/argoproj/argo-events/issues/262 .
> fix validating payloads from github

- gateways/community/gcp-pubsub/Dockerfile
- gateways/community/gcp-pubsub/start.go
- gateways/event-sources.go
> fix gcp-pubsub-gateway

- gateways/core/calendar/start.go
> fix timezone bug

- hack/k8s/manifests/kustomization.yaml
Very simple base [kustomize](https://kustomize.io/) configuration.
Signed-off-by: Michael Goodness <mgoodness@gmail.com>
> Add kustomization.yaml

- sensors/trigger.go
Passing namespace to dynamicResInterface.Create method.
> added namespace to create obj

- Gopkg.lock
- gateways/community/storagegrid/start.go
- gateways/transformer.go
current code will have error when doing go build without module
> fix uuid with correct return value

- README.md
😄  As requested in [Slack](https://argoproj.slack.com/archives/CAM37QYMS/p1575658870319800)
> Add Viaduct.ai to Who Uses Argo Events Section

- README.md
> Change Viaduct.ai to Viaduct

- README.md
Added Community Blogs and Presentations section
> chore: Add Community Blogs and Presentations

- hack/k8s/manifests/kustomization.yaml
> fix: fix kustomization.yaml

- hack/k8s/manifests/argo-events-cluster-roles.yaml
Was getting permission denied to create apps.deployments in namespace <my namesapce> until i changed this.
> fix RBAC roles

- docs/installation.md
> Update installation doc

- examples/event-sources/gitlab.yaml
changed keyword from gitlabBaseUrl to gitlabBaseURL
> fix: gitlabBaseURL keyword change

- sensors/triggers/standard-k8s/starndard-k8s.go
- sensors/triggers/standard-k8s/starndard-k8s_test.go
Signed-off-by: VaibhavPage <vaibhav.page@gmail.com>
> fix(k8s-update-operation): fix the k8s update operation

- examples/event-sources/aws-sqs.yaml
> Fix sqs example event source

- docs/quick_start.md
Make dependency on Argo Workflows installed in the cluster explicit
The final verification step will fail without this.
> Improve getting started guide

- gateways/client/cloud-events.go
> fix(nats-subscribers): fix gateway nats subscribers logic

- api/event-source.html
- api/event-source.md
- api/gateway.html
- api/gateway.md
- api/sensor.html
- api/sensor.md
- gateways/server/gitlab/start.go
- pkg/apis/eventsources/v1alpha1/openapi_generated.go
- pkg/apis/eventsources/v1alpha1/types.go
> feat(gitlab-gateway): check for duplicate webhooks

- CONTRIBUTING.md
- api/event-source.html
- api/event-source.md
- api/gateway.html
- api/gateway.md
- api/sensor.html
- api/sensor.md
- controllers/sensor/operator.go
- controllers/sensor/resource.go
- controllers/sensor/validate.go
- pkg/apis/sensor/v1alpha1/types.go
> docs: align messages with renaming

- sensors/triggers/http/http.go
> fix: use configured method for HTTP trigger

- CONTRIBUTING.md
- sensors/triggers/params.go
> feat: Set nested JSON properties in sensor trigger payload

- Gopkg.lock
- api/openapi-spec/swagger.json
- api/sensor.html
- api/sensor.md
- controllers/sensor/validate.go
- docs/triggers/k8s-object-trigger.md
- pkg/apis/sensor/v1alpha1/openapi_generated.go
- pkg/apis/sensor/v1alpha1/types.go
- sensors/triggers/standard-k8s/starndard-k8s.go
- sensors/triggers/standard-k8s/starndard-k8s_test.go
Signed-off-by: VaibhavPage <vaibhav.page@gmail.com>
> feat(trigger-patch-op): added patch operation

- api/gateway.html
- api/gateway.md
- api/openapi-spec/swagger.json
- controllers/gateway/resource.go
- pkg/apis/gateway/v1alpha1/openapi_generated.go
- pkg/apis/gateway/v1alpha1/types.go
- pkg/apis/gateway/v1alpha1/zz_generated.deepcopy.go
> feat: add affinity, tolerations in template and clusterIP in service. Closes #663.

- gateways/client/state_test.go
- gateways/server/aws-sqs/start.go
- gateways/server/common/aws/aws_test.go
- hack/library.sh
- hack/update-api-docs.sh
- hack/update-codegen.sh
- hack/update-openapigen.sh
- hack/upgrade-k8s-version.sh
Time cost of `make codegen` with this:
```
real	0m52.473s
user	1m19.281s
sys	0m21.820s
```
Old:
```
real	9m34.158s
user	16m29.026s
sys	13m53.991s
```
> chore: Improve the performance of make codegen

- api/event-source.html
- api/event-source.md
- gateways/server/kafka/start.go
- pkg/apis/eventsource/v1alpha1/openapi_generated.go
- pkg/apis/eventsource/v1alpha1/types.go
We we always getting a failure to connect to kafka with non tls this fixes that after looking a bit into the sarama docs look like config needs to be nil when passed in or needs to have its NewConfig function called.
> fix: Fix kafka gateway

- docs/tutorials/01-introduction.md
file docs/tutorials/01-introduction.md
typo fix
> chore: small typo fix

- docs/FAQ.md
👋 This patch includes some quick fixes that should help with the readability of the FAQ page in the Argo Events documentation. ✏️ 
Thank you for the great work on Argo Events, and I hope to be making more PRs soon! 🎉
> chore: improve faq documentation

- docs/tutorials/07-filters.md
- pkg/apis/sensor/v1alpha1/types.go
- sensors/dependencies/filter.go
- sensors/dependencies/filter_test.go
Fixes https://github.com/argoproj/argo-events/issues/808.
> feat: Add `NotEqualTo` comparator to data filters

- controllers/eventbus/installer/nats.go
> fix(eventbus): update NATS log path to be together with data path. Fixes #832

- Dockerfile
Updated sensor base image to `alpine` to gain more security.
> chore: Sensor base image change

- controllers/eventbus/controller.go
- controllers/eventsource/controller.go
- controllers/sensor/controller.go
Fixes #800
Support `semaphore` feature of argo.
> chore: upgade argo cli to v2.10.x

- Makefile
- api/openapi-spec/swagger.json
- hack/gen-openapi-spec/main.go
- hack/update-swagger.sh
> chore: Refine swagger file with referenced k8s specs

- docs/installation.md
The doc mentions extra steps for Openshift based installation.
This PR adds the actual command, for interested users on how to grant `anyuid` for Openshift's `securitycontextconstraints`
> docs: Improve Openshift note 

- .dockerignore
- .github/workflows/docker-image.yml
- Dockerfile
- Dockerfile.dev
- Makefile
- hack/image_arch.sh
Reworked the Makefile to be in similar to: https://github.com/argoproj/argo/blob/master/Makefile
Reworked the Dockerfile to be in sync with: https://github.com/argoproj/argo/blob/master/Dockerfile
Added a CI to push images: https://github.com/dgiebert/argo-events/runs/1011429452
Needed Secrets:
- DOCKERIO_USERNAME
- DOCKERIO_PASSWORD
- DOCKERIO_ORG
Automatically releases master and tags, see e.g. here: https://hub.docker.com/repository/docker/dgiebert/eventbus-controller
Closes: https://github.com/argoproj/argo-events/issues/836
> ci: Adapted Makefile to argo

- Makefile
- api/event-source.html
- api/event-source.md
- api/openapi-spec/swagger.json
- api/sensor.html
- api/sensor.md
- common/retry.go
- controllers/eventbus/installer/exotic_nats.go
- eventbus/driver/nats.go
- eventsources/eventing.go
- eventsources/sources/amqp/start.go
- eventsources/sources/emitter/start.go
- eventsources/sources/kafka/start.go
- eventsources/sources/mqtt/start.go
- eventsources/sources/nats/start.go
- eventsources/sources/nsq/start.go
- eventsources/sources/pulsar/start.go
- eventsources/sources/util.go
- pkg/apis/eventsource/v1alpha1/generated.proto
- pkg/apis/eventsource/v1alpha1/openapi_generated.go
- pkg/apis/eventsource/v1alpha1/types.go
- pkg/apis/sensor/v1alpha1/generated.proto
- pkg/apis/sensor/v1alpha1/openapi_generated.go
- pkg/apis/sensor/v1alpha1/types.go
- sensors/listener.go
- sensors/trigger.go
Code rafactory and a bugfix for Makefile - order matters for `eventsource` and `eventsource-controller`, `sensor` and `sensor-controller`.
> chore: code refactory and cleaning up unused code

- api/openapi-spec/swagger.json
- hack/gen-openapi-spec/main.go
- hack/update-swagger.sh
Definitions like `EventSourceList` are necessary for clients generation such as https://github.com/argoproj-labs/argo-events-client-java.
> chore: Update swagger file to include unused definitions.

- store/git.go
> feat: cloneDirectory not required for git source trigger

- .github/pull_request_template.md
- README.md
- USERS.md
> chore: Update PR template. Closes #875

- common/logging/logger.go
> chore: update log.info output to stdout. Fixes #884.

- docs/triggers/http-trigger.md
> docs: correct typo in http trigger

- docs/tutorials/03-trigger-sources.md
> fix(doc): complaint => compliant

- USERS.md
> docs: add 3Rein to USERS

- api/event-bus.html
- api/event-bus.md
- api/event-source.html
- api/event-source.md
- api/openapi-spec/swagger.json
- api/sensor.html
- api/sensor.md
- docs/tutorials/02-parameterization.md
- examples/event-sources/calendar.yaml
- examples/event-sources/gcp-pubsub.yaml
- pkg/apis/common/generated.proto
- pkg/apis/common/openapi_generated.go
- pkg/apis/common/s3.go
- pkg/apis/eventbus/v1alpha1/generated.proto
- pkg/apis/eventbus/v1alpha1/openapi_generated.go
- pkg/apis/eventbus/v1alpha1/types.go
- pkg/apis/eventsource/v1alpha1/generated.proto
- pkg/apis/eventsource/v1alpha1/openapi_generated.go
- pkg/apis/eventsource/v1alpha1/types.go
- pkg/apis/sensor/v1alpha1/generated.proto
- pkg/apis/sensor/v1alpha1/openapi_generated.go
- pkg/apis/sensor/v1alpha1/types.go
> docs: fix typos

- USERS.md
> chore: add user to list

- eventsources/sources/generic/start.go
> fix(generic-eventsource): Set payload when jsonbody is not true. Fix #930

- Makefile
> fix(build): broken build script

- docs/quick_start.md
> docs: Update quick_start.md

- docs/concepts/event_source.md
> docs: Update event_source.md

- README.md
> docs: Sort triggers in README.md

- CONTRIBUTING.md
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Checklist:
Ref #881
> docs: correct go version in contrib docs

- sensors/dependencies/filter.go
- sensors/dependencies/filter_test.go
Support comparator EqualTo and NotEqualTo in Data filters for Strings
> feat: Add string comparators EqualTo and NotEqualTo

- README.md
> docs: add cii best practices

- CONTRIBUTING.md
> docs: Add test policy

- .github/workflows/release.yml
- test/manifests/kustomization.yaml
> fix: Build and publish latest images automatically

- docs/concepts/trigger.md
> docs: add log to trigger.md

- .github/workflows/release.yml
> chore: Allow release testing

- sensors/triggers/slack/slack.go
> fix: correcting the value of Types

- docs/index.md
Add the link to the video that explains Events
> docs: Video

- go.mod
- go.sum
- hack/crdgen.sh
- hack/crds.go
- manifests/base/crds/argoproj.io_eventbus.yaml
- manifests/base/crds/argoproj.io_eventsources.yaml
- manifests/base/crds/argoproj.io_sensors.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
> chore: update CRD version to apiextensions.k8s.io/v1

- common/util.go
- common/util_test.go
Originally TLS config requires all of `caCert`, `clientCert` and `clientKey` are configured, which is not right.
This change makes all of following cases valid:
1. Only `caCert` is configured;
2. Only `clientCert` and `clientKey` are configured;
3. All of `caCert`, `clientCert` and `clientKey` are configured.
Checklist:
> fix: make caCert, clientCert and clientKey optional for tls config

- pkg/apis/common/common.go
- pkg/apis/common/validate.go
- pkg/apis/common/validate_test.go
> fix: tls config validation, follow up on #1070

- docs/eventbus.md
> Add missing apiVersion to EventBus example

- .github/workflows/gh-pages.yaml
> chore: add a github action to auto build gh-pages

- Makefile
> chore: Add release related commands

- docs/eventsources/calendar-catch-up.md
- examples/event-sources/calendar.yaml
> docs: Add missing RBAC requirements for calendar catch-up

- api/event-source.html
- api/event-source.md
- api/openapi-spec/swagger.json
- api/sensor.html
- api/sensor.md
- pkg/apis/common/common.go
- pkg/apis/common/generated.proto
- pkg/apis/common/openapi_generated.go
- pkg/apis/eventsource/v1alpha1/generated.proto
- pkg/apis/eventsource/v1alpha1/openapi_generated.go
- pkg/apis/eventsource/v1alpha1/types.go
- pkg/apis/sensor/v1alpha1/generated.proto
- pkg/apis/sensor/v1alpha1/openapi_generated.go
- pkg/apis/sensor/v1alpha1/types.go
Comments for deprecation.
Need to state these in v1.3 release.
Checklist:
> chore: deprecation in v1.5 comments 

- docs/quick_start.md
> fix(docs): Update link to Argo Workflows

- USERS.md
Signed-off-by: Tianchu Zhao <evantczhao@gmail.com>
Checklist:
> docs(user): add user to list

- test/stress/generator/cmd/root.go
- test/stress/testdata/sensors/log.yaml
> fix(stress-testing): only check total requests when it is specified

- Makefile
> chore: Update version in Makefile during release preparation

- docs/eventsources/setup/github.md
> docs: fix gitlab -> github

- docs/metrics.md
Use v1 API for RBAC.
Signed-off-by: Shoubhik Bose <shbose@redhat.com>
Checklist:
> chore: use ClusterRole v1

- pkg/apis/eventsource/v1alpha1/types_test.go
- pkg/apis/sensor/v1alpha1/types_test.go
> chore: Add missing test cases

- controllers/eventbus/installer/installer.go
- eventbus/driver/nats.go
- eventsources/cmd/main.go
- eventsources/common/webhook/webhook.go
- eventsources/sources/gcppubsub/start.go
- sensors/cmd/main.go
- sensors/listener.go
> chore: use zap.SugaredLogger instead of zap.Logger

- common/retry.go
- common/retry_test.go
> fix: Backoff retry should not swallow errors. Fixes #1166

- README.md
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
Checklist:
> docs: Update link to the new CNCF Slack channel

- eventsources/sources/awssns/start.go
> fix: Fast fail invalid SNS notification. Fixes: #1182

- .github/workflows/snyk.yaml
- go.mod
- go.sum
> ci: Run Snyk vulnerability check

- common/retry.go
- common/retry_test.go
- pkg/apis/common/int64str.go
> fix: Retry duration recognizes strings. Fixes #1200

- Dockerfile
> chore: build sensor image from scratch

- USERS.md
- examples/sensors/github.yaml
Straightforward example showing `argo-events` power and how to interact with `Github` attributes
> docs: Enriched github example

- examples/sensors/log-debug.yaml
Added a basic doc example with debug log enabled.
> docs(argo-events): Added example with debug log enabled

- docs/FAQ.md
> docs(argo-events): Add link to FAQ on debug

- api/sensor.md
> chore: re-run codegen

- docs/sensors/trigger-conditions.md
Fixed wrong indentation in the yaml spec :)
Checklist:
> docs: fix trigger dependencies yaml

- USERS.md
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
Checklist:
> docs: Add Alibaba and Ant Group to USERS.md

- USERS.md
https://www.linkedin.com/company/wooliesx/
Signed-off-by: Tianchu Zhao <evantczhao@gmail.com>
Checklist:
> docs(users): Add WooliesX

- examples/sensors/amqp.yaml
- examples/sensors/aws-sns.yaml
- examples/sensors/aws-sqs.yaml
- examples/sensors/azure-events-hub.yaml
- examples/sensors/calendar.yaml
- examples/sensors/data-filter-webhook.yaml
- examples/sensors/emitter.yaml
- examples/sensors/file.yaml
- examples/sensors/filter-with-expressions.yaml
- examples/sensors/gcp-pubsub.yaml
- examples/sensors/hdfs.yaml
- examples/sensors/kafka.yaml
- examples/sensors/mqtt-sensor.yaml
- examples/sensors/multi-dependencies.yaml
- examples/sensors/nsq.yaml
- examples/sensors/pulsar.yaml
- examples/sensors/redis.yaml
- examples/sensors/resource.yaml
- examples/sensors/slack.yaml
- examples/sensors/special-workflow-trigger.yaml
- examples/sensors/storage-grid.yaml
- examples/sensors/stripe.yaml
- examples/sensors/trigger-standard-k8s-resource.yaml
- examples/sensors/trigger-with-policy.yaml
- examples/sensors/webhook.yaml
> fix(docs): add missing dataKey for examples

- USERS.md
I joined [Ubie](https://ubie.life/en). As we use Argo Workflows, Events and Rollouts, I added the company to the users.
Checklist:
> docs: Add ubie to users

- go.mod
- go.sum
> fix: Upgrade pkg to v0.10.1

- docs/index.md
"Insufferable" is my middle name.
Checklist:
^ Why would I do that... is that required? I'm not contributing this PR as an employee of my company.
> Improve grammar

- USERS.md
- sensors/triggers/standard-k8s/standar-k8s.go
> fix: Added cluster resources support in k8s trigger

- USERS.md
- eventsources/sources/amqp/validate.go
> Fix: amqp allow empty exchange name

- manifests/base/eventbus-controller/eventbus-controller-deployment.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- third_party/nats-streaming-docker/README.md
- third_party/nats-streaming-docker/update.sh
- third_party/prometheus-nats-exporter-docker/README.md
- third_party/prometheus-nats-exporter-docker/amd64/Dockerfile
> chore: update 3rd party dependencies

- controllers/sensor/validate.go
- docs/quick_start.md
- examples/sensors/special-workflow-trigger-shortened.yaml
- examples/sensors/trigger-standard-k8s-resource-shortened.yaml
- examples/sensors/webhook-shortened.yaml
- sensors/triggers/fetch.go
- sensors/triggers/standard-k8s/standar-k8s.go
- sensors/triggers/triggers.go
- sensors/triggers/triggers_test.go
> feat: Removed usage of redundant GVR fields in k8s/workflow triggers

- eventsources/common/webhook/webhook.go
> fix: mask auth secret. Fixes: #1336

- go.mod
- go.sum
> chore: upgrade mongo-driver due to vulnerability alert

- SECURITY.md
> chore: vulnerabilities report contacts change

- docs/quick_start.md
> fix:(doc): quick start link

- .github/workflows/ci.yaml
- api/event-bus.md
- api/event-source.md
- api/sensor.md
- hack/crdgen.sh
- hack/crds.go
- hack/generate-proto.sh
- hack/library.sh
> chore: fix crdgen issue after upgrading

- examples/sensors/url-sensor.yaml
> docs(example): fix url sensor argo-workflow link

- eventsources/eventing.go
- sensors/listener.go
> fix: fatal the services if starting failed

- .github/workflows/gh-pages.yaml
> chore: pin python version for gh-pages

- docs/installation.md
the helm chart has been updated since a while
> docs: remove note about helm 2 requirement

- sensors/triggers/params.go
- sensors/triggers/params_test.go
> fix: Eval of params with missing src dep and no default value

- USERS.md
Add GHGSat
Signed-off-by: Tho Nguyen <thnguyen@ghgsat.com>
Checklist:
> chore: Add organization to USERS.md

- sensors/triggers/triggers.go
- sensors/triggers/triggers_test.go
> fix: Added plural exception for eventbus resource for k8s trigger

- eventsources/sources/github/appauth.go
- eventsources/sources/github/start.go
- eventsources/sources/github/tokenauth.go
- eventsources/sources/github/types.go
- eventsources/sources/github/validate.go
- go.mod
- go.sum
> chore: fix a security issue caused by ghinstallation

- go.mod
> chore: retract accidental v1.15.0

- api/jsonschema/schema.json
- hack/jsonschema/main.go
> fix: int-or-string k8s type in jsonschema

- docs/eventbus.md
> docs: more eventbus customization

- docs/sensors/triggers/nats-trigger.md
> docs: MinIO event source link updated in docs

- docs/sensors/triggers/k8s-object-trigger.md
The `delete` operation is already implemented with https://github.com/argoproj/argo-events/pull/1041 but not yet documented.
> docs: Extend k8s trigger with delete operation

- Dockerfile
> chore: upgrade workflow binary to v3.2.4

- docs/dr_ha_recommendations.md
> docs: add pdb recommendation for EventBus

- docs/eventbus.md
> docs: typo eventbus

- examples/sensors/minio.yaml
The parameters is a field of StandardK8sTrigger based on this https://github.com/argoproj/argo-events/blob/master/api/sensor.md#standardk8strigger
Checklist:
> docs: fix parameters in MinIO example

- USERS.md
> docs: Add Gllue to list of users

- sensors/triggers/params.go
> fix: Sensor triggers an Argo Workflow with wrong name

- eventsources/eventing.go
- sensors/listener.go
> fix: let the service restart after leader switched

- eventbus/driver/nats.go
> fix: conditions reset honors the latest timestamp of all unacked msgs. Fixes: #1522

- docs/sensors/transform.md
> fix(docs): Fix doc about event transform release date

- go.mod
- go.sum
fixes https://github.com/argoproj/argo-events/discussions/1521
see https://github.com/tidwall/gjson/issues/260#issuecomment-1012294762
Checklist:
* [] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).
> chore: upgrade gjson to get get fromstring feature

- docs/eventsources/multiple-events.md
> fix: Removed "limitation" from outdated doc

- OWNERS
> chore: add daniel-codefresh as a reviewer

- Makefile
- common/common.go
- common/util.go
- controllers/eventsource/resource.go
- controllers/sensor/resource.go
- docs/developer_guide.md
- hack/library.sh
- manifests/base/sensor-controller/sensor-controller-deployment.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- test/manifests/kustomization.yaml
> chore: develop with k3d cluster

- eventsources/sources/generic/start.go
- go.mod
- go.sum
- sensors/triggers/custom-trigger/custom-trigger.go
Signed-off-by: William Van Hevelingen <william.vanhevelingen@acquia.com>
Checklist:
> chore(deps): bump google.golang.org/grpc from v1.42.0 to v1.43.0

- SECURITY.md
Signed-off-by: Henrik Blixt <henrikblixt@gmail.com>
Checklist:
> chore:Updating security.md

- .github/workflows/snyk.yaml
> chore: Only run Snyk daily on master. Fixes #1593

- .github/dependabot.yml
> chore: Force dependabot to only open 1 PR at a time. Fixes #1592

- README.md
- docs/security.md
- mkdocs.yml
> docs: Make SECURITY.md easy to discover. Fixes #1594

- docs/eventsources/filtering.md
Created documentation to detail how to use event source filtering and to update with examples and use cases.
> docs: create filtering.md

- eventsources/sources/amqp/start.go
Fixes #1545: Username/password authentication for AMQP
> Fix: Issue 1545: Username/password authentication for AMQP

- docs/concepts/event_source.md
- go.mod
- mkdocs.yml
> chore: retract and docs

- manifests/extensions/validating-webhook/rbac/argo-events-webhook-cluster-role.yaml
- manifests/install-validating-webhook.yaml
- webhook/cmd/start.go
- webhook/webhook.go
- webhook/webhook_test.go
> fix: Garabge collection of the ValidatingWebhookConfiguration

- go.mod
- go.sum
- sensors/triggers/slack/slack.go
Signed-off-by: Alok Naushad <alokme123@gmail.com>
This fixes #1612 
Checklist:
> chore: slack dependency upgrade

- .github/workflows/release.yml
> chore: Fix SBOM generation. Fixes #1571

- docs/eventsources/setup/bitbucketserver.md
- examples/event-sources/bitbucketserver.yaml
- examples/sensors/bitbucketserver.yaml
> docs: Added Bitbucket Server docs

- docs/installation.md
Signed-off-by: danielm-codefresh <daniel.maizel@codefresh.io>
Checklist:
> fix: Openshift support for the Validating Admission Webhook

- docs/concepts/event_source.md
- mkdocs.yml
> docs: Added Bitbucket Server docs to Setup nav

- USERS.md
Fixes docs: Add SAP Concur
Signed-off-by: Tomas Valasek tomas.valasek@sap.com
Checklist:
> docs: Add SAP Concur

- USERS.md
Checklist:
* [ x] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).
> docs: Yubo added to users

- docs/managed-namespace.md
Was a little confused by the documentation. I think this is what's meant, right?
Checklist:
> docs: rewording for clarification

- go.mod
- go.sum
> chore: security fix for nats-streaming

- docs/managed-namespace.md
- docs/quick_start.md
- docs/tutorials/01-introduction.md
> docs: adding clarification for how to configure Argo Workflows to interoperate with Argo Events

- .github/workflows/dependabot-reviewer.yml
> build: Automated dependabot reviews. Fixes #1769

- examples/sensors/minio.yaml
> fix: example for minio (sensor yaml)

- .github/workflows/gh-pages.yaml
- mkdocs.yml
> fix: broken gh-pages build

- eventbus/jetstream/base/jetstream.go
Fixes #1808 
Mitigation until NATS maintainers address underlying issue
Checklist:
> fix: adding retry logic for Stream creation in the case that another client is trying to create the Stream at the same time

- examples/tutorials/06-trigger-conditions/sensor-01.yaml
- examples/tutorials/06-trigger-conditions/sensor-02.yaml
Signed-off-by: lsl-msft <shileiliu@microsoft.com>
Checklist:
Fix #1871 
As is described in title, fix examples in tutorial to make sure it provides expected outputs.
> fix: example for trigger conditions tutorial (minio put/delete trigger's dataKey value)

- SECURITY.md
- docs/concepts/trigger.md
- docs/dr_ha_recommendations.md
- docs/eventbus.md
- docs/eventsources/gcp-pubsub.md
- docs/eventsources/ha.md
- docs/eventsources/naming.md
- docs/eventsources/setup/amqp.md
- docs/eventsources/setup/aws-sns.md
- docs/eventsources/setup/bitbucket.md
- docs/eventsources/setup/gcp-pub-sub.md
- docs/eventsources/setup/github.md
- docs/eventsources/setup/gitlab.md
- docs/index.md
- docs/installation.md
- docs/metrics.md
- docs/sensors/filters/data.md
- docs/sensors/filters/expr.md
- docs/sensors/filters/intro.md
- docs/sensors/more-about-sensors-and-triggers.md
- docs/sensors/trigger-conditions.md
- docs/sensors/triggers/aws-lambda.md
- docs/sensors/triggers/http-trigger.md
- docs/sensors/triggers/slack-trigger.md
- docs/service-accounts.md
- docs/tutorials/01-introduction.md
- docs/tutorials/06-trigger-conditions.md
- docs/tutorials/07-policy.md
- test/stress/README.md
Signed-off-by: Jesse Antoszyk <22500761+jcantosz@users.noreply.github.com>
Checklist:
> docs: fix some typos in the markdown documentation

- controllers/cmd/start.go
- manifests/cluster-install/rbac/argo-events-cluster-role.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/namespace-install/rbac/argo-events-role.yaml
This implements leader Election for the argo-events controller as mentioned in #1565 
Closes: #1565
> feat: Controller Leader Election

- .github/workflows/ci.yaml
> ci: e2e build for jetstream driver

- docs/sensors/filters/intro.md
- docs/sensors/filters/script.md
- examples/sensors/filter-script.yaml
- mkdocs.yml
> docs: script filter introduction

- mkdocs.yml
> docs: Redis streams tutorial

- docs/sensors/filters/intro.md
> docs: Sensor filters doc fix - correct number of types

- .github/dependabot.yml
> chore: dependency bot frequency change

- USERS.md
> docs: Add Softonic to list of users

- sensors/listener.go
Signed-off-by: Derek Wang <Derek_Wang@intuit.com>
Fixes: #1953
Checklist:
> chore: do not return nil since it is never used

- manifests/base/controller-manager/controller-config.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
> chore: jetstream new version and reloader image change

- controllers/eventbus/controller.go
- controllers/eventsource/controller.go
- controllers/sensor/controller.go
- eventsources/sources/awssqs/start.go
- eventsources/sources/gitlab/start.go
Signed-off-by: Derek Wang <Derek_Wang@intuit.com>
Closes: #1952
Checklist:
> chore: clean up unused function parameters

- eventsources/sources/bitbucketserver/start.go
- eventsources/sources/bitbucketserver/validate.go
- pkg/apis/eventsource/v1alpha1/types.go
> fix: make Bitbucket Server access token optional

- controllers/eventbus/installer/jetstream.go
- controllers/eventbus/installer/jetstream_test.go
- fixed incorrect resource setting on buildStatefulSetSpec
Checklist:
> fix: jetstream statefulset resource setting

- .github/dependabot.yml
> chore: ignore sigs.k8s.io/controller-runtime update

- OWNERS
> docs: Add @whynowy as sub-project lead

- docs/eventsources/ha.md
> docs: add bitbucketserver to HA doc

- examples/event-sources/bitbucket.yaml
> fix: update bitbucket es example yaml

- sensors/triggers/params.go
> fix: return error in case param value resolving fails

- eventsources/sources/bitbucket/start.go
This PR solves #2110 and is a POC for all Git related eventsources. It solves the `deleteHookOnFinish` race condition and removes the need in "hooks manager daemon" mitigation that exists in all Git related eventsources and leads to API rate limit exhaustion.
The solution is quite simple:
The main reason that we are facing a race condition when `deleteHookOnFinish` is enabled is that the new eventsource pod is trying to use the same hook that could possibly be deleted by the old eventsource pod. My suggestion is that every new eventsource pod would "recreate" the hook incase it already exists (delete the old hook and create a new one) instead of using the previous one, so that each eventsource pod would work against a different hook subscribtion with a different ID. This way no …
> fix: Stop Bitbucket API rate limit exhaustion by solving deleteHookOnFinish race condition

- docs/installation.md
> docs: we only have one Controller now

- eventsources/eventing.go
> feat: retry failed eventbus message publishing

- common/retry.go
- common/retry_test.go
> fix: error is swallowed after retry failure

- USERS.md
Adding Elastic to the user list
Signed-off-by: Christopher Cutajar <60098546+christophercutajar@users.noreply.github.com>
> Adding Elastic as an Argo Events Users

- docs/eventbus/jetstream.md
- manifests/base/controller-manager/controller-config.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
> chore: enable jetstream 2.9

- examples/event-sources/calendar.yaml
> chore: fix examples to drop deprecated fields

- Dockerfile
- manifests/base/controller-manager/controller-config.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
> chore: enable argo v3.4 and nats 2.9.1

- USERS.md
As we are heavily using the argo ecosystem for the management of our OpenShift Clusters and applications as well as implementing our CICD solutions we would like to reflect that on the users list :) 
Checklist:
> docs: add Gepardec to users

- api/event-source.html
- api/event-source.md
- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- pkg/apis/eventsource/v1alpha1/generated.proto
- pkg/apis/eventsource/v1alpha1/openapi_generated.go
- pkg/apis/eventsource/v1alpha1/types.go
Signed-off-by: Prema devi Kuppuswamy <premadk@gmail.com>
Checklist:
> fix(docs): partition as optional field for kafka eventsource fixes: #1502

- .github/workflows/dependabot-reviewer.yml
One workflow got missed in PR #2281, as part of issue #2250
> chore: fixed workflow permissions

- USERS.md
- eventsources/sources/kafka/start.go
Signed-off-by: Nick Palumbo <npalumbo8@bloomberg.net>
for https://github.com/argoproj/argo-events/issues/2358
Checklist:
> Make kafka eventsource compatible with samara 1.37.0 Addresses #2358

- docs/quick_start.md
Checklist:
This PR:
- updates a stale installation link for Argo Workflows
- reminds users to create namespaces
> docs: fix missing link and add missing instructions

- docs/eventsources/setup/nats.md
- eventsources/sources/nats/start.go
- pkg/apis/events/event-data.go
> NATS event data - add header field

- .github/workflows/release.yml
- sensors/artifacts/git.go
- sensors/artifacts/git_test.go
- sensors/triggers/kafka/kafka.go
Fixes: #2406
As well as a github action bugfix.
Checklist:
> fix: cloneDirectory validation on git artifcatory spec

- USERS.md
@whynowy  You may want to add a note to avoid using GitHub's web text editor as this automatically converts the numbering as soon as you press enter at the end of the line like this:
Checklist:
> Add Pinnacle Reliability to user list

- USERS.md
> Add Salesforce in USERS.md

- .github/workflows/ci.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/release.yml
- Makefile
- USERS.md
- docs/developer_guide.md
- go.mod
- third_party/prometheus-nats-exporter-docker/amd64/Dockerfile
Checklist:
Fixes: https://github.com/argoproj/argo-events/issues/2484
> Chore: go1.20

- .github/workflows/release.yml
> fix(ci): setup-go treat 1.20 as 1.2

- docs/eventbus/kafka.md
Include recommendation of when it makes sense to a Kafka EventBus and more details on the configuration options.
Checklist:
> docs: Update kafka eventbus docs

- Makefile
> fix: make start to also work with arm64

- eventbus/jetstream/sensor/trigger_conn.go
> feat: update log level for some lines to Info and expand logged fields

- docs/installation.md
Enhance helm installation instructions.
By invitation https://github.com/argoproj/argo-helm/issues/840#issuecomment-1549649125
Checklist:
> docs: Update helm installation

- manifests/base/controller-manager/kustomization.yaml
- manifests/base/crds/kustomization.yaml
- manifests/base/kustomization.yaml
- manifests/cluster-install/kustomization.yaml
- manifests/cluster-install/rbac/kustomization.yaml
- manifests/extensions/validating-webhook/kustomization.yaml
- manifests/namespace-install/kustomization.yaml
- manifests/namespace-install/rbac/kustomization.yaml
- test/manifests/kafka/kustomization.yaml
- test/manifests/kustomization.yaml
Checklist:
fix #2701 
updated kustomization.yaml using 'kustomize edit fix'.
> chore: support kustomize v5

- eventbus/jetstream/sensor/sensor_jetstream.go
- eventsources/sources/pulsar/start.go
- go.mod
- go.sum
Checklist:
fix #2699
Just updating pulsar-client-go will fix it.
> chore: update pulsar to v0.11.0

- .github/workflows/ci.yaml
- sensors/dependencies/filter.go
- sensors/triggers/params.go
It adds all sprig functions to templates. 
Related issue [2766](https://github.com/argoproj/argo-events/issues/2766)
> feat: add all sprig functions to templates

- OWNERS
dtaniwaki is no longer active in argoproj. See https://github.com/argoproj/argoproj/blob/master/MAINTAINERS.md#alumni
> docs: Update OWNERS

- api/event-bus.html
- api/event-bus.md
- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- controllers/eventbus/installer/jetstream.go
- pkg/apis/eventbus/v1alpha1/generated.proto
- pkg/apis/eventbus/v1alpha1/jetstream_eventbus.go
- pkg/apis/eventbus/v1alpha1/openapi_generated.go
> fix: Cert hosts for JetStream EventBus

- docs/eventsources/setup/mqtt.md
Correct the mqtt link
Checklist:
> fix(docs): Update mqtt.md

- test/e2e/testdata/sensor-atleastonce-fail.yaml
- test/e2e/testdata/sensor-atmostonce-fail.yaml
- test/e2e/testdata/sensor-test-metrics.yaml
This url is reserved by IANA and is expected to always fail resolution.
Checklist:
> Replace url https://not-existing.com/ with https://invalid.com/ (#2993)

- eventbus/kafka/base/kafka_test.go
Adding test coverage for: https://github.com/argoproj/argo-events/blob/master/eventbus/kafka/base/kafka.go
Checklist:
> adding base/kafka_test.go for code coverage

- docs/tutorials/01-introduction.md
The tutorial does not explain how to view logs to confirm the event worked.
Checklist:
> docs: Provides command to view logs

- USERS.md
- docs/eventbus/jetstream.md
Checklist:
Addresses https://github.com/argoproj/argo-events/issues/2692
> docs: update on using custom jetstream version

- pkg/eventsources/sources/azurequeuestorage/start.go
> fix: decode base64-encoded messages from Azure Storage Queue

- go.mod
- go.sum
- pkg/shared/leaderelection/leaderelection.go
- pkg/shared/leaderelection/leaderelection_test.go
> chore: bump up dependencies and fix lint problem

- go.mod
- go.sum
- pkg/sensors/triggers/kafka/kafka.go
Fixes: https://github.com/argoproj/argo-events/issues/3415
Checklist:
> fix: CVE-2023-37475

- Dockerfile
> chore: bump up workflow binary version

- .github/workflows/release.yml
> fix(ci): use actions/upload-artifact v4

- pkg/apis/events/v1alpha1/sensor_types.go
> Fix typo that emits a malformed JSON string.

- .github/workflows/release.yml
> fix(ci): upgrade actions/upload-artifact

- docs/eventsources/setup/alibabacloud-mns.md
- mkdocs.yml
Checklist:
* [x ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).
This is  follow up PR for https://github.com/argoproj/argo-events/pull/3550
> doc: add alibaba cloud mns/smq doc

- Dockerfile
Checklist:
This PR updates the Argo Workflow version to 3.6.10
> chore: Update Argo WF version in Dockerfile. Closes #3606
